ministryofjustice/licences

assets/sass/application.scss
server.js
server/app.js
server/index.js
server/routes/reportingInstructions.js
server/services/reportingInstructionsService.js
server/views/reportingInstructions/index.pug
test/routes/reportingInstructionsTest.js
test/services/reportingInstructionsServiceTest.js

First stab at dependency injection for this route

added reporting ui with hardcoded data and dependency injection

---

assets/sass/application.scss
server/app.js
server/authentication/auth.js
server/authentication/signIn.js
server/routes/signIn.js
server/views/layout.pug
server/views/login.pug

The user profile comes from the nomis mock and is just as below. Now gets put in req.user and the views can access it from the "profile" var, which goes in via res.locals as per HPA.
Stuck a logout route in cos we'll need one eventually
```
"firstName": "staff",
"lastName": "user",
"staffId": "1",
"email": "staff.user@work",
"activeCaseLoadId": "ABC"
```

Put full user profile in session, show user in header, add logout link

---

server/data/licenceClient.js
server/routes/dischargeAddress.js
server/views/dischargeAddress/index.pug
test/data/licenceClientTest.js
test/routes/dischargeAddressTest.js

Removed nomis address lookup.
Address page shows input form only.
JSON MODIFY uses JSON QUERY to avoid escaping nested JSON

Address form

---

server/data/meta/additionalConditionsMeta.js
server/services/conditionsService.js
test/services/conditionsServiceTest.js

Added meta data to new map. 
Will want to look at whether this would be better in the db a little further down the line.

added ui info to conditions

---

server/routes/licenceDetails.js
server/services/licenceService.js
server/utils/licenceFactory.js
server/views/licenceDetails/additionalConditions.pug
test/services/licenceServiceTest.js
test/utils/licenceFactoryTest.js

First step, still using map in code rather than db.
No grouping of conditions yet

inject additional conditions into licence and display

---

migrations/20171026101742_create-conditions-table.js
seeds/a004-conditions.js

I give up trying to make a proper migration. You'll have to drop all the tables and run migrate from scratch.
Could migrate by dropping the table entirely and making a new one but something isn't working and I don't know what or why.
If we were in prod I'd have to create a new table, copy all the data across, and drop the old one, so I'm glad we're not in prod..

Fixed IDs for conditions

---

server/app.js
server/config.js

Use env var for test utils

---

assets/sass/application.scss
seeds/a003-staff-ids.js
server/authentication/signIn.js
server/data/licenceClient.js
server/data/nomisClientBuilder.js
server/routes/caseList.js
server/services/caseListService.js
server/views/caseList/CATable.pug
server/views/caseList/ROTable.pug
server/views/caseList/index.pug
test/data/licenceClientTest.js
test/data/nomisClientTest.js
test/routes/caseListTest.js
test/services/caseListServiceTest.js
test/supertestSetup.js

https://dsdmoj.atlassian.net/browse/LIC-96

LIC-96 added functionality to get RO case list

---

server/models/models.js
server/routes/config/licenceConditions.js
server/routes/licenceConditions.js
server/views/licenceConditions/curfewAddressReviewForm.pug
server/views/licenceConditions/includes/landlordHDCConsent.pug
server/views/proposedAddress/confirmAddressForm.pug
server/views/proposedAddress/includes/preferredAddress.pug
test/routes/licenceConditionsTest.js

This PR only add a page template for now called `/hdc/proposedAddress/curfewAddressConfirmation/A0001XX`
Resolves [155](https://dsdmoj.atlassian.net/browse/LIC-155)

Add Proposed address curfew for a RO user

---

server/routes/taskList.js
server/utils/licenceTaskState.js
server/views/send/ROtoCA.pug
server/views/taskList/submitTask.pug
test/routes/taskListTest.js
test/utils/licenceTaskStateTest.js

I moved the task state completion thing into a separate file.
Added a check for all tasks being complete in order to enable the Submit task.
For now, it treats STARTED as DONE, because we don't have DONE yet.
If any task is UNSTARTED, the Submit button isn't shown

Send Ro to CA

---

server/routes/config/eligibility.js
server/routes/config/licenceConditions.js
server/routes/config/proposedAddress.js
server/routes/hdc.js
server/utils/routes.js
server/views/licenceConditions/curfewHoursForm.pug
test/utils/routesTest.js

In this PR, I add test and refactor the routes config.
As an aside I've added default times for the curfew hours based on the designs

LIC-219: Connect routes

---

server/data/licenceClient.js
server/data/taskStates.js
server/models/licenceStages.js
server/models/roles.js
server/models/taskStates.js
server/routes/send.js
server/services/licenceService.js
server/utils/licenceTaskState.js
server/views/send/index.pug
test/routes/eligibilityTest.js
test/supertestSetup.js

Better names for eg licenceStage rather than state
Put role/taskState/licenceState names in consistent/central place

Better/Fixed names for roles, tasks states, processing stages

---

server/utils/licenceStatusLabels.js
server/views/caseList/index.pug
server/views/eligibility/crdTime.pug
server/views/eligibility/excluded.pug
server/views/eligibility/includes/excluded.pug
server/views/eligibility/includes/suitability.pug
server/views/eligibility/suitability.pug
server/views/licenceDetails/curfewAddress.pug
server/views/proposedAddress/bassReferral.pug
server/views/proposedAddress/curfewAddress.pug
server/views/proposedAddress/includes/otherResidents.pug
server/views/proposedAddress/includes/preferredAddress.pug
server/views/proposedAddress/optOut.pug
server/views/taskList/prisonerDetails.pug
server/views/taskList/taskList.pug
test/routes/eligibilityTest.js
test/routes/proposedAddressTest.js
test/utils/licenceStatusLabelsTest.js

https://dsdmoj.atlassian.net/browse/LIC-237
and
https://dsdmoj.atlassian.net/browse/LIC-238
**Builds on earlier PRs - review oldest one first**

Lic 237+238

---

server/routes/config/finalChecks.js
server/routes/hdc.js
server/utils/licenceStatus.js
server/utils/licenceStatusTransitions.js
server/views/curfew/curfewHours.pug
server/views/finalChecks/onRemand.pug
server/views/finalChecks/postpone.pug
server/views/finalChecks/seriousOffence.pug
server/views/taskList/additionalConditionsTask.pug
server/views/taskList/caSubmitTask.pug
server/views/taskList/finalChecksTask.pug
server/views/taskList/includes/utils.pug
server/views/taskList/postponementTask.pug
server/views/taskList/taskList.pug
test/routes/finalChecksTest.js
test/routes/taskListTest.js
test/supertestSetup.js
test/utils/licenceStatusTest.js
test/utils/licenceStatusTransitionsTest.js

Disable send to DM when tasks not complete
Final checks task
Placeholder for postponement

Final checks

---

assets/sass/application.scss
server/views/curfew/curfewAddressReview.pug
server/views/proposedAddress/includes/addressDetail.pug
server/views/review/address.pug

https://dsdmoj.atlassian.net/browse/LIC-293

Update address layout

---

package.json
server/routes/config/proposedAddress.js
server/services/licenceService.js
server/services/utils/licenceValidation.js
test/services/licenceServiceTest.js
yarn.lock

First iteration of validation of licence. Will likely need to evolve in terms of what is returned to caller when we know how it will be used.
Maybe incorporate validation config into existing form config if it doesn't make too much of a mess

First steps for implemintation of licence validation

---

server/app.js
server/views/review/includes/curfewAddress.pug

Also redirect 404 to stop false BDD test pass

Fix address review change details path

---

server/routes/config/proposedAddress.js
server/routes/hdc.js
server/services/utils/licenceValidation.js
test/services/licenceServiceTest.js

Because we are validating on review, the licence has been constructed to not have address in array

updated address validation to not look for array

---

seeds/a004-conditions.js
server/views/proposedAddress/includes/addressForm.pug
server/views/taskList/finalChecksTask.pug
server/views/taskList/optOutTask.pug
server/views/taskList/proposedAddressTask.pug
test/routes/taskListTest.js
test/services/prisonerServiceTest.js

https://dsdmoj.atlassian.net/browse/LIC-350

LIC-350: Update prisoner references to offender

---

server/views/taskList/finalChecksTask.pug

https://dsdmoj.atlassian.net/browse/LIC-368

LIC-368: Update working of serious offence question

---

server/utils/licenceStatusLabels.js
server/views/caseList/CATable.pug
test/utils/licenceStatusLabelsTest.js

https://dsdmoj.atlassian.net/browse/LIC-346

Show address rejected in CA caselist

---

seeds/a004-conditions.js
seeds/a005-conditions-ui.js
seeds/a006-conditions-groups.js
server/models/conditions.js
server/services/utils/licenceValidation.js
server/utils/licenceFactory.js
server/views/licenceConditions/includes/attendSampleDetails.pug
server/views/licenceConditions/includes/formBuilder.pug
test/services/licenceServiceTest.js
test/utils/licenceFactoryTest.js

Part of https://dsdmoj.atlassian.net/browse/LIC-227

Add PSS conditions

---

assets/sass/application.scss
server/views/taskList/taskList.pug

LIC-265: Add presumed unsuitable banner

---

assets/sass/application.scss
server/routes/config/curfew.js
server/routes/hdc.js
server/utils/addressHelpers.js
server/utils/licenceStatus.js
server/views/proposedAddress/includes/addressDetail.pug
server/views/review/address.pug
server/views/review/includes/addressActions.pug
server/views/taskList/curfewAddressTask.pug
server/views/taskList/taskList.pug
test/routes/curfewTest.js
test/routes/reviewTest.js
test/utils/licenceStatusTest.js

First half of the work to add address withdrawal feature

CA can withdraw address during final checks

---

server/views/curfew/curfewHours.pug

https://dsdmoj.atlassian.net/browse/LIC-453

Remove words and reduce spacing

---

server/utils/licenceStatusLabels.js
test/utils/licenceStatusLabelsTest.js

https://dsdmoj.atlassian.net/browse/LIC-494

Update status labels

---

server/views/review/curfewAddress.pug

But not when in normal final checks

Allow edit address link during withdraw address route

---

server/data/nomisClientBuilder.js
server/services/config/pdfData.js
server/services/utils/formatForView.js
server/views/send/templates/roToCaTemplate.pug
test/data/nomisClientTest.js
test/services/utils/formatForViewTest.js
test/services/utils/pdfFormatterTest.js

and take first BUS phone number for licence PDF

Update nomis API calls

---

server/authentication/signInService.js
server/config.js
test/authentication/signInTest.js

Also increase timeout for nomis calls

Throw error on oauth refresh failure

---

server/utils/licenceStatus.js
test/utils/licenceStatusTest.js

https://dsdmoj.atlassian.net/browse/LIC-513

Reporting instructions task only DONE when all answered

---

server/views/taskList/caSubmitAddressReviewTask.pug
server/views/taskList/taskList.pug

https://dsdmoj.atlassian.net/browse/LIC-522

Show submit button when address task has been started, even if not done

---

server/utils/licenceStatus.js

https://dsdmoj.atlassian.net/browse/LIC-518

Undo what was previously asked to be do

---

server/routes/pdf.js
server/services/config/pdfData.js
server/views/pdf/tasks/reportingTask.pug
server/views/pdf/tasks/sentenceInfoTask.pug
server/views/pdf/tasks/taggingTask.pug
test/services/utils/pdfFormatterTest.js

LIC-550
Change which fields are considered mandatory when deciding whether to allow creating PDF, to only include the fields that appear on the create licence tasklist.

Make mandatory field list match fields shown in create licence tasklist

---

server/utils/licenceStatus.js
server/views/caseList/CATable.pug
server/views/caseList/alt/CATable.pug
server/views/proposedAddress/rejected.pug
server/views/taskList/tasks/curfewAddressTask.pug
server/views/taskList/tasks/proposedAddressTask.pug

https://dsdmoj.atlassian.net/browse/LIC-546

Clarefication

---

server/routes/config/authorisation.js
server/routes/config/bassReferral.js
server/routes/send.js
server/services/config/formsAndSections.js
server/services/config/validationMessages.js
server/services/licenceService.js
server/services/utils/licenceValidation.js
server/utils/licenceStatus.js
server/utils/licenceStatusLabels.js
server/utils/licenceStatusTransitions.js
server/views/bassReferral/bassAreaCheck.pug
server/views/bassReferral/bassRequest.pug
server/views/review/includes/bassArea.pug
server/views/review/includes/licenceSummary.pug
server/views/review/licenceDetails.pug
server/views/sent/mixins/sentCaMixin.pug
server/views/sent/roToCa.pug
server/views/sent/roToCaAddressRejected.pug
server/views/sent/roToCaOptedOut.pug
server/views/taskList/caTasksPostApproval.pug
server/views/taskList/includes/startContinueChangeButton.pug
server/views/taskList/roTasks.pug
server/views/taskList/tasks/bassAddressTask.pug
test/routes/bassReferralTest.js
test/services/licenceServiceTest.js
test/utils/licenceStatusLabelsTest.js
test/utils/licenceStatusTest.js
test/utils/licenceStatusTransitionsTest.js

RO BASS area check
(sorry - couldn't make it any smaller)

RO BASS area check

---

server/services/config/validationMessages.js
server/services/config/validationRules.js
server/services/licenceService.js
server/services/utils/licenceValidation.js

With a view to reworking validation I have started by splitting out from licenceService

separate validation logic from licenceService

---

docker-compose.yml
package-lock.json
package.json
server/app.js
server/authentication/auth.js
server/authentication/authInit.js
server/authentication/signInService.js
server/config.js
server/data/nomisClientBuilder.js
server/services/userService.js
server/utils/fiveMinutesBefore.js
server/views/autherror.pug
test/authentication/authInitTest.js
test/authentication/signInTest.js
test/mockAuthentication.js
test/routes/signinTest.js
test/services/userServiceTest.js

fixed auth callback use to get. Throw error if required role is not present
Fixed tests

added oauth2 functionality behind feature switch

---

server/routes/config/bassReferral.js
server/services/utils/formValidation.js
test/services/formValidationTest.js

LIC-803-BASS-validation

---

server/routes/config/bassReferral.js
server/services/utils/formValidation.js
server/views/taskList/tasks/createLicenceTask.pug
test/services/formValidationTest.js

Enable create licence when BASS address completed

LIC-802-BASS-create-licence-rules

---

server/views/bassReferral/bassOffer.pug
server/views/review/bassOffer.pug
server/views/taskList/caTasksFinalChecks.pug
server/views/taskList/caTasksPostApproval.pug
server/views/taskList/tasks/proposedAddressTask.pug

Revert to proposedAddressTask when new entry requires RO review

LIC-805-post-decision-rejection-flows

---

package.json
seeds/a003-staff-ids.js
server/routes/config/notificationMailboxes.js
test/routes/sendTest.js

also disable commit hook tests because incompatible with GitKraken

Config for test emails in stage

---

.eslintrc.json

Put back previously agreed team rules

Restore no-console lint rule

---

server/routes/send.js
server/services/notificationService.js
test/routes/sendTest.js
test/services/notificationServiceTest.js

Also remove unnecessary API call because prisoner personal details already in request scope

Add NOMS number to notifications

---

server/services/config/notificationMailboxes.js

This is going to be replaced in the next story with DB storage and an admin UI to support more establishments
see - https://dsdmoj.atlassian.net/browse/LIC-923

Temporary - DM notification email addresses

---

server/data/nomisClientBuilder.js
server/services/config/approvalStatuses.js
test/services/nomisPushServiceTest.js

https://dsdmoj.atlassian.net/browse/LIC-949
- correct code value for presumed unsuitable
- log error details when present

Correct PRES UNSUIT approval status code

---

licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/specs/assessment/LicenceDetailsSpec.groovy
licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/specs/review/ReviewLicenceSpec.groovy
server/routes/viewModels/taskLists/roTasks.js
server/views/review/includes/licenceSummary.pug
test/routes/viewModels/taskListModelsTest.js

Also make bass rejection and address rejection consistent

Make tasklist and check details rules consistent with each other

---

server/services/config/approvalStatuses.js
test/services/nomisPushServiceTest.js

Requires new refusal reason to be defined in NOMIS

Temporarily remove nomis push for servingRecall

---

server/services/prisonerService.js
test/services/prisonerServiceTest.js

Where there are two or more relationships of type ResponsibleOfficer assigned to an offender in NOMIS:
Previously we were using the one with the highest person ID and getting the delius ID for that person
However, the delius ID may not always exist, so now we lookup the delius ID for each person ID,
If there are still multiple delius IDs, pick the one with the highest person id

Where multiple relations, get all ids, ignore missing / select highest

---

server/app.js
server/config.js
server/index.js
server/routes/config/authorisation.js
server/routes/forms.js
server/services/formService.js
server/services/utils/pdfFormatter.js
test/routes/formsTest.js
test/services/formServiceTest.js
test/supertestSetup.js

Immediately throw if unknown template

Form creation route and service

---

server/app.js

Correct missing service wiring

LIC-844 Nomis push on opt out

---

server/config.js
server/services/notificationService.js
test/services/notificationServiceTest.js

See also https://dsdmoj.atlassian.net/wiki/spaces/LIC/pages/1393918299/Notifications

Get active templates from env var

---

server/routes/config/authorisation.js
server/routes/viewModels/taskLists/tasks/additionalConditions.js
server/utils/licenceStatus.js
server/views/review/conditions.pug
test/utils/licenceStatusTest.js

Also allows CA to edit conditions in Final Checks

Warnings in Final Checks when rejected or incomplete bespoke conditions

---

package-lock.json
package.json

results of npm audit fix
(NB can't update jquery because it breaks things)

Update dependency versions (for security patches)

---

server/services/config/approvalStatuses.js
test/services/nomisPushServiceTest.js

See also https://dsdmoj.atlassian.net/wiki/spaces/LIC/pages/1428783438/NOMIS+Push
https://dsdmoj.atlassian.net/browse/LIC-1003

Add secondary reason for approval status push for serving recall

---

licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/modules/AddressDetailsModule.groovy
licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/pages/assessment/LicenceDetailsPage.groovy
licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/specs/assessment/LicenceDetailsSpec.groovy
licences-specs/src/test/resources/licences/assessment/address-incomplete.json
server/services/utils/formValidation.js
server/views/review/includes/curfewAddress.pug
server/views/review/includes/licenceSummary.pug
server/views/review/risk.pug
test/services/formValidationTest.js

Fixes for problems described in LIC-1013.  They correct missing or incorrect error messages and missing text on the review/licenceDetails page.

LIC-1013 "There is a problem" displayed in RO check details screen

---

.gitignore
assets/sass/pdf.scss
licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/specs/assessment/TaskListSpec.groovy
package-lock.json
package.json
server/app.js
server/config.js
server/routes/config/authorisation.js
server/routes/forms.js
server/routes/viewModels/taskLists/roTasks.js
server/services/conditionsService.js
server/views/forms/curfewAddress.pug
server/views/forms/includes/bassArea.pug
server/views/forms/includes/conditions.pug
server/views/forms/includes/curfewAddressReview.pug
server/views/forms/includes/offender.pug
server/views/forms/includes/prisonCompleted.pug
server/views/forms/includes/probationCompleted.pug
server/views/forms/includes/proposedAddress.pug
server/views/forms/includes/reporting.pug
server/views/forms/includes/risk.pug
server/views/forms/includes/victim.pug
server/views/review/includes/licenceSummary.pug
test/routes/formsTest.js
test/routes/viewModels/taskListModelsTestRO.js
test/services/conditionsServiceTest.js
test/supertestSetup.js

https://dsdmoj.atlassian.net/browse/LIC-1010
https://dsdmoj.atlassian.net/wiki/spaces/LIC/pages/1493008534/Curfew+Address+Check+Form+PDF

Generate curfew address check form using express-pug-pdf

---

server/routes/forms.js
server/services/conditionsService.js
server/services/formService.js
server/views/forms/curfewAddress.pug
server/views/forms/includes/approvedPremises.pug
server/views/forms/includes/probationCompleted.pug
server/views/forms/includes/proposedAddress.pug
test/routes/formsTest.js
test/services/conditionsServiceTest.js
test/services/formServiceTest.js

- fix bug when standard conditions only
- remove landlord address details - we never have it
- remove RO email because we don't know where to get it from yet
- add Approved Premises address details when AP required

Add support for AP, remove landlord details

---

server/app.js
server/config.js
server/routes/forms.js
server/routes/pdf.js
server/views/forms/forms-layout.pug

Tweak to ensure that the CSS documents are requested from the port used by the Node.JS server.

LIC-1041 PDF documents not rendering in preprod environment

---

server/config.js
server/routes/pdf.js
server/services/pdfService.js
server/views/licences/hdc_ap_pss.pug
server/views/licences/hdc_pss.pug
server/views/licences/hdc_u12.pug
server/views/licences/hdc_yn.pug
server/views/licences/includes/curfewTimes.pug
server/views/licences/includes/licenceHeader.pug
server/views/licences/includes/licenceMixins.pug
server/views/licences/vary_hdc_ap.pug
test/routes/pdfTest.js
test/services/pdfServiceTest.js

Migrate licence templates and one licence vary templates to new PDF renderer

LIC-1032 Lic-1031 

---

server/views/licences/vary_hdc_u12.pug

…f-generator template, but present in old NOMIS version).

LIC-1032 Fix missing paragraph in vary_hdc_u12

---

data-load/README.md
data-load/staff-ids-load.sh
data-load/user-load.sh

These were the scripts used to load the North East user data and will be useful for other regions to follow.

Onboarding scripts, user and staff mapping load scripts and instructions.

---

data-load/README.md
data-load/user-load.sh

README.md and user-load.sh changes only.

Loading of licence-vary users for the North East & script updates to support this.

---

server/config.js
server/index.js
server/services/config/notificationTemplates.js
server/services/notificationService.js
server/utils/functionalHelpers.js
test/services/notificationServiceTest.js
test/utils/functionalHelpersTest.js

LIC-1063 Send e-mail notification direct to the Responsible Officer.
LIC-1059 Use new email templates for messages copied to clearing office.

LIC-1063, LIC-1059

---

Notes.md
licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/specs/pdf/PdfSpec.groovy
licences-specs/src/test/resources/licences/decision/approved-missing.json
server/app.js
server/data/licenceClient.js
server/routes/pdf.js
server/routes/viewModels/taskListModels.js
server/routes/viewModels/taskLists/varyTasks.js
server/services/pdfService.js
server/utils/licenceStatus.js
server/utils/versionInfo.js
server/views/pdf/tasks/createLicenceTask.pug
server/views/pdf/tasks/firstNightTask.pug
server/views/pdf/tasks/reportingTask.pug
server/views/pdf/tasks/sentenceInfoTask.pug
server/views/pdf/tasks/varyApprovalTask.pug
test/routes/pdfTest.js
test/services/pdfServiceTest.js
test/supertestSetup.js
test/utils/licenceStatusTest.js
test/utils/versionInfoTest.js

Also fixes problems with pre and post release version numbers incrementing inappropriately.
This should cover LIC-1073 'Changing the licence template type is updating the licence version minor number'.

LIC-1068 Case list status not changing to Licence Created

---

package-lock.json
package.json
server/services/deliusRoService.js
test/services/deliusRoServiceTest.js

Also upgrading a couple of libraries

LIC-1085 Handling 404 errors when retrieving managed offenders. 

---

server/services/notificationService.js

in preparation for adding the ro's org's email address

DCS-182 de-ramdafying some code 

---

licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/pages/assessment/LicenceConditionsAdditionalPage.groovy
licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/specs/assessment/LicenceConditionsSpec.groovy
licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/specs/assessment/LicenceConditionsSummarySpec.groovy
licences-specs/src/test/resources/GebConfig.groovy
server/routes/conditions.js
server/routes/config/licenceConditions.js
server/routes/forms.js
server/services/conditionsService.js
server/services/config/conditionsConfig.js
server/services/utils/bespokeConditionsSchema.js
server/services/utils/pdfFormatter/index.js
server/services/utils/pdfFormatter/pdfFormatter.js
server/views/licenceConditions/includes/appointmentName.pug
server/views/licenceConditions/includes/courseOrCentre.pug
server/views/review/includes/additionalConditions.pug
test/services/formValidationTest.js
test/services/utils/pdfFormatterTest.js
test/stubs/conditions.js

A user was previously unable to record the issues the prisoner needs to address as part of his/her Licence Conditions. 
Have added a new set of checkboxes in the hdc/licenceConditions/additionalConditions page that define each of the Abuse and Behaviours.
Upon making a selection from these checkboxes and navigating to the hdc/licenceConditions/conditionsSummary page, the user can then see the selections they have made, inside the main body text of the page.
The selections made will also be displayed in the PDF of the licence given to the prisoner.

Dcs 205 error in how licence condition is displaying

---

licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/specs/decision/ApprovalTaskListSpec.groovy
server/routes/viewModels/taskLists/dmTasks.js
server/views/review/conditions.pug

* Decision Maker given amend/delete option of (additional) licence conditions when it should be view only.
* Also refactor/tidy up dmTasks.js

DCS-225 HDC 

---

licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/specs/decision/ApprovalTaskListSpec.groovy
licences-specs/src/test/resources/licences/decision/risks-rejected.json
server/routes/viewModels/taskLists/caTasks.js
server/routes/viewModels/taskLists/dmTasks.js
test/routes/viewModels/taskListModelsTestDM.js

DCS-181 HDC - Risk Management Information not displaying for the Decision Maker. 

---

licences-specs/README.md
server/services/caseListService.js

Also tidying up caseListService - removing need to pass services around everywhere

DCS-230 Removing reference to testing in stage (which doesn't exist)

---

server/data/deliusClient.js
server/routes/admin/delius.js
server/services/deliusRoService.js
server/views/admin/delius/index.pug
server/views/admin/delius/staffDetails.pug
test/data/deliusClientTest.js
test/services/deliusRoServiceTest.js

also adding ability to make these calls via the admin page

DCS-248 Adding delius calls in to retrieve staff 

---

server/data/deliusClient.js
server/index.js
server/services/jobs/notificationJobs.js
server/services/notificationService.js
server/services/reminderService.js
server/views/admin/delius/managedOffenders.pug
test/services/jobSchedulerServiceTest.js
test/services/jobs/notificationJobsTest.js
test/services/notificationServiceTest.js
test/services/reminderServiceTest.js

Also fixing broken admin offender look up page when no offender data present

DCS-233 Extracting out reminder functionality from notification service.

---

server/app.js
server/index.js
server/routes/admin/delius.js
server/services/roService.js
test/services/roServiceTest.js

Previously there used to be 2 roServices but now we only have one

DCS-233 renaming deliusROService to roService 

---

server/data/deliusClient.js
server/index.js
server/services/notifications/caAndDmNotificationSender.js
server/services/notifications/notificationService.js
server/services/notifications/roNotificationSender.js
server/services/roContactDetailsService.js
server/services/roService.js
test/data/deliusClientTest.js
test/services/notifications/caAndDmNotificationSenderTest.js
test/services/notifications/notificationServiceTest.js
test/services/notifications/roNotificationSenderTest.js
test/services/roContactDetailServiceTest.js
test/services/roServiceTest.js
types/delius.d.ts
types/licences.d.ts

Refactoring sending RO notifications so that we always ensure we have enough info before sending the notifications.

DCS-248 Calling new delius service for retrieving staff details 

---

migrations/20191202091906_create-active-local-delivery-units-table.js
server.js
server/data/activeLduClient.js
test/data/activeLduClientTest.js

New table created to hold the Local Delivery Unit codes.
The presence of a code means that particular Local Delivery Unit is 'active'

DCS-263: new migration file to create LDU table

---

seeds/a003-staff-ids.js
server/data/nomisClientBuilder.js
server/services/caseListService.js
server/services/userService.js
server/utils/Result.js
server/utils/ResultTypes.d.ts
test/services/caseListServiceTest.js
test/utils/Result.test.js
types/elite2api.d.ts

Integration tests must be run against an updated licences-demo-mock service to succeed.

DCS-280 Extend staff id look up to call delius for missing users.

---

server/routes/taskList.js

removed if block because if errorCodesList will be [] then errors will be [] which is handleable by the front end

DCS:264: removed unnecessary 'if' block

---

server/routes/taskList.js
server/routes/viewModels/taskListModels.js
server/routes/viewModels/taskLists/caTasks.js

Moving tasklist for when a CA is blocked in with the rest of the CA tasks.

DCS-304 Refactoring blocked CA tasklist

---

server/routes/config/taskListErrors.js
server/routes/taskList.js
server/routes/viewModels/taskLists/caTasks.js
server/views/taskList/taskListBuilder.pug
server/views/taskList/tasks/caBlockedTask.pug
test/routes/taskList.test.js

This is WIP as need to check some content but all hidden behind a feature switch.
This also fixes existing bug where we would show the error messages when the eligibility section was only partially complete

DCS-304 Updating message content for when a CA is blocked. 

---

server/data/probationTeamsClient.js
server/services/notifications/roNotificationHandler.js

Will log info messages when:
1. fail to get a functional mailbox
2. RO role assigned to user

DCS-333: log messages

---

server/app.js

locations was auditing against WARNINGs, 
licence search defaulted to UPDATE_SECTION

Fixing audit keys

---

licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/specs/assessment/LicenceConditionsSpec.groovy
server/views/licenceConditions/includes/appointmentDetails.pug
server/views/licenceConditions/includes/courseOrCentre.pug
test/services/utils/pdfFormatter.test.js

http://localhost:3000/hdc/licenceConditions/additionalConditions/{bookingId}
New checkbox for 'drug abuse' added to the 'comply' component of the Drugs Health,and Behaviour section.
Unnecessary comments removed from appointmentDetails.pug

DCS-319 New checkbox option added

---

azure/licences_log_queries.txt

There ought (and probably is) a better way to share these queries, but for now I've added them to the licences project...

(Possibly) Useful Azure log queries

---

server/routes/config/licenceConditions.js
server/services/config/conditionsConfig.js
test/services/formValidation.test.js
test/stubs/conditions.js

http://localhost:3000/hdc/licenceConditions/additionalConditions/{bookingId}
The words 'drug abuse' are needed in the label to fully describe the options available when the checkbox is selected.

DCS-319-checkbox label includes the words 'drug abuse'

---

licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/pages/assessment/ProposedAddressCurfewAddress.groovy
licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/pages/assessment/ProposedAddressCurfewAddressChoice.groovy
licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/pages/assessment/ProposedAddressRejectedPage.groovy
licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/specs/assessment/ProposedAddressRejectedSpec.groovy
licences-specs/src/test/resources/GebConfig.groovy
server/routes/address.js
server/routes/config/proposedAddress.js
server/utils/functionalHelpers.js
server/views/includes/alternativeForm.pug
server/views/proposedAddress/rejected.pug
test/routes/address.test.js
test/supertestSetup.js

http://localhost:3000/hdc/proposedAddress/rejected/{bookingId}
Previously user could 'save and continue' without selecting the yes/no radio. This was incorrect  behaviour so have added validation checking. Now user is redirected back to the same page until they make a selection

DCS-347: user must select a radio button before they can move on

---

README.md
docker-compose.yml
server/config.js

Find it annoying to keep having to swap docker images around when moving between working on different services.

Moving ports used in local dev to be consistent with other dps projects.

---

azure/licences_log_queries.txt
server/data/deliusClient.js
server/data/nomisClientBuilder.js
test/data/nomisClient.test.js

Dropping level to warn if call fails as this was producing double error logging

DCS-349 Adding additional logging to clients.

---

helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

Flip feature switch 'CJA2003_SZA ' so that new behaviour can be deployed to preprod & prod environments

DCS-389 Enable new ineligibility and presumed unsuitable reasons 

---

test/services/formValidation.test.js

'_12/03/2020_'? **It'll never happen!**

DCS-395 fix broken test

---

server/services/formService.js
server/services/utils/pdfFormatter/pdfFormatter.js
server/utils/functionalHelpers.js
test/services/formService.test.js
test/utils/functionalHelpers.test.js

This is a fix for a bug introduced by DCS-224

DCS-430 approved form does not render

---

server/routes/taskList.js
server/routes/viewModels/taskListModels.js
server/utils/licenceStatusTransitions.js
test/routes/viewModels/taskListModelsCA.test.js
test/routes/viewModels/taskListModelsRO.test.js

Pushing logic down to where its used

DCS-391 starting to refactor the concept of suitable transitions.

---

server/routes/viewModels/taskListModels.js
server/utils/licenceStatusTransitions.js
test/utils/licenceStatusTransitions.test.js

DM tasks never use transition type.

DCS-391 removing unused transition logic for DM

---

tsconfig.json

change needed because npm run start:dev throwing erorrs

DCS-458: change to ts-config

---

assets/sass/application.scss
server/utils/licenceStatus.js
server/views/taskList/taskListTemplate.pug
test/routes/taskList.test.js

The comments appear only after the DM had made a decision providing the decision is a refusal.
The comments appear in the orange bordered box at the top of the CA tasklist.

DCS-411: CA can view the DMs HDC decision comments

---

server/views/taskList/taskListTemplate.pug

Spacing added between title and DM comments.
Hyphens changed to colon.

DCS-411: Changes to HDC refusal reason box, as per Andy Hudson

---

server/routes/viewModels/taskLists/tasks/createLicence.js
test/routes/viewModels/taskLists/tasks/createLicence.test.js

Reverting change here: https://github.com/ministryofjustice/licences/pull/1156/files#diff-a942ed4d58632523079f43ae15b5a39e

DCS-477 Reverting broken tidy up which lead to inability to create licences

---

server/routes/viewModels/taskLists/tasks/ca/refuseHdc.js
server/utils/licenceStatus.js
server/views/taskList/taskListTemplate.pug
test/routes/viewModels/taskLists/tasks/ca/refuseHdc.test.js
test/utils/licenceStatus.test.js

Also fixing refuse button - it previously never changed value even if refused
This is because it was looking at the wrong decision
Tidied up the logic for displaying warning message too.

DCS-476 Showing reason when CA refuses case before DM handover

---

Dockerfile

Use 
`CMD [ "node", "server.js" ] `
instead of 
`CMD [ "npm", "start" ]`

DCS-253 Fix docker build 

---

licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/specs/common/CommonCaselistSpec.groovy
licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/specs/decision/CaselistSpec.groovy
server/services/caseListService.js
server/views/admin/functionalMailboxes/lduWithTeams.pug
server/views/caseList/DMTable.pug
test/services/caseListService.test.js

This corresponds with cases in stage APPROVAL, DECIDED, MODIFIED or MODIFIED_APPROVAL.

DCS-479 DM Caselist: Show all cases sent to DM or with PCA after this step

---

README.md
loadLicences
saveLicences

There are no production changes in this PR.

DCS-498 Scripts to save and restore the licences table

---

README.md
package.json
server/loadLicences.js
server/saveLicences.js

Now they can be added to the PATH using 'npm link'

DCS-498 Add loadLicences.js and saveLicences.js scripts to package.json

---

package-lock.json
package.json
server/collectAuditStatistics.ts
server/collectLicenceStatistics.ts
server/loadLicences.js
server/saveLicences.js
server/statistics/AuditStatisticsCollector.ts
server/statistics/LicenceStatisticsCollector.ts
server/statistics/booking.ts
server/statistics/d3adapter.ts
server/statistics/tableReader.ts
server/statistics/types.ts
test/statistics/AuditStatisticsCollector.test.ts
test/statistics/Booking.test.ts
test/statistics/d3adapter.test.ts

There are no production changes in this PR.
Two scripts `collectAuditStatistics.ts` and `collectLicenceStatistics.ts` which output statistics describing the aggregate state of the HDC application.

DCS-525 Statistics scripts

---

.circleci/config.yml
docker-compose.yml
licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/specs/TaskListGuardSpec.groovy
licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/specs/common/WebsiteSpec.groovy
licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/util/Actions.groovy
server/authentication/roles.js
server/routes/config/authorisation.js
server/routes/review.ts
server/routes/taskList.ts
server/services/caseListService.ts
server/services/licence/licenceStatusLabels.js
server/services/userService.js
server/services/utils/caseListFormatter.js
server/views/caseList/CATable.pug
server/views/caseList/index.pug

Use `LICENCE_READONLY` role instead of `PRISON`.

DCS-317 Read-only access for prison staff who do not have the CA, DM or RO role.

---

server/collectLicenceStatistics.ts
server/collectMoreLicenceStatistics.ts
server/data/nomisClientTypes.ts
server/statistics/AuditStatisticsCollector.ts
server/statistics/RowCollector.ts
server/statistics/rowFilter.ts
server/statistics/sentenceSource.ts
server/statistics/tableReader.ts
server/statistics/types.ts
test/statistics/licenceStatisticsCollector.test.ts
test/statistics/rowFilter.test.ts

Add a new script to collect additional statistics.  Doesn't affect any production code.

DCS-552 Identify incomplete applications in the service

---

server/data/userClient.js
server/services/migrationService.ts
test/data/userClient.test.js
test/services/migrationService.test.ts

Also adding new require vary flag and fix email check to be case insensitive

DCS-608 fix delete via UI to use soft delete

---

server/data/userClient.js
server/routes/contact.js
server/services/roContactDetailsService.js
server/services/userAdminService.js
test/data/userClient.test.js
test/routes/contact.test.js
test/services/roContactDetailService.test.js

when retrieving contact details

DCS-609 Use delius username to link to staff data from local store 

---

server/routes/viewModels/taskLists/caTasks.js
test/routes/viewModels/taskListModelsCA.test.js

Remove 'Create licence' task when postponed.

DCS-480 Postpone an approved licence.

---

log.js
package-lock.json
package.json
server/app.js

Stop using the Winston Console transport when application insights is used.

DCS-604 Prevent logging of post requests in licences

---

server/utils/renderPdf.ts

As described here: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md\#tips

DCS-775 Adding option to disable shm in bid to solve OOM issues

---

Dockerfile
docker-compose-full.yml
docker-compose.yml
package.json
server/utils/renderPdf.ts

:bug: Configure the Docker image according to the latest puppeteer recommendations.

DCS-755: Bug fix for rendering PDFs.

---

licences-specs/README.md

Updated readme with clearer instructions for running integration tests. 
The primary reason for this ticket was to verify whether a user is logged out when a second user logs in. 
Have manually produced the steps in DEV environment to confirm that this is the case.

DCS-824: updated readme 

---

server/views/forms/agency_notification.pug
server/views/forms/licence_variation.pug
test/routes/forms.test.js

new forms to download and view: 
[licence variation.pdf](https://github.com/ministryofjustice/licences/files/6229623/licence.variation.pdf)
[agency notification.pdf](https://github.com/ministryofjustice/licences/files/6229625/agency.notification.pdf)

DCS 924 HDC add acquisitive question

---

server/views/caseList/index.pug

This change applies to the Case list page only

DCS-896 change of style and text of link leading back to DPS.

---

assets/sass/application.scss
assets/sass/change-location.scss
licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/pages/CaselistPage.groovy
licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/specs/common/CommonCaselistSpec.groovy
licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/util/Actions.groovy
mock-server/routes/users.js
server/services/userService.js
server/views/layout.pug
server/views/user/admin.pug
test/services/userService.test.js

User can view and change their location, aka caseload, from any page in the app.
This action was previously done by user via the DPS service.
Showing the 'Change location' link is conditional on user having more than 1 location.
Showing the current location is dependant on user having a currentlyActive caseload

DCS-1160 Caseload actions added to each page

---

server/data/licenceClient.ts
server/data/licenceClientTypes.ts
server/routes/conditions.ts
server/routes/config/licenceConditions.js
server/services/licenceService.ts
test/mockServices.ts
test/routes/licenceConditions.test.ts
test/services/licenceService.test.ts

Still need to consider the following: 
* When should conditions version be persisted if not previously set? (Its possible for a user to never select an optional question)
* Add migration
* Read value when populating list

DCS-1248 Persisting conditions 

---

migrations/20211123165443_rename-condition-version.js
migrations/20211123172816_set-additional-conditions-version.js
server/data/licenceClient.ts
server/data/licenceClientTypes.ts
server/routes/conditions.ts
server/services/licenceService.ts
test/data/licenceClient.test.ts
test/mockServices.ts
test/routes/licenceConditions.test.ts
test/services/licenceService.test.ts

Renaming conditions version to additional conditions version
Migrating existing licences with additional conditions to the existing version

DCS-1248 Persisting additional conditions version

---

README.md
helm_deploy/licences/templates/_envs.tpl
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml
server/services/licenceService.ts
test/services/licenceService.test.ts

DCS-1166 Clearing out conditions version when resetting licence

---

helm_deploy/values-preprod.yaml

bootstrap script has been run for preprod

DCS-1384 direct preprod traffic to live

---

database_refresh/03-prometheus-alert.yaml

This isn't automated so I've manually applied the change and updating here for future reference

DCS-1672 Update alert channel for refresh job

---

package-lock.json

DCS-1892: 🤖 Fix Security Vulnerabilities

DCS-1892: 🤖 Fix Security Vulnerabilities

---

server/views/bassReferral/bassRequest.pug
test/routes/bassReferral.test.js

DCS-2172 content change to curfew address h2

---

licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/specs/eligibility/BassRequestSpec.groovy
licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/specs/eligibility/EligibilityTaskListSpec.groovy
server/routes/viewModels/taskLists/tasks/ca/submitBassReview.js
test/routes/viewModels/taskListModelsCA.test.js
test/routes/viewModels/taskLists/tasks/ca/submitBassReview.test.js

DCS-2173 ca eligibility tasklist heading change

---

server/views/review/includes/bassArea.pug
server/views/review/includes/licenceSummary.pug

DCS-2175 ca eligibility licence review page content change

---

licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/specs/assessment/BassAreaSpec.groovy
licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/specs/assessment/TaskListSpec.groovy
server/routes/viewModels/taskLists/tasks/ro/bassArea.js
server/views/bassReferral/bassAreaCheck.pug
test/routes/bassReferral.test.js
test/routes/viewModels/taskListModelsRO.test.js
test/routes/viewModels/taskLists/tasks/ro/bassArea.test.js

Change for DCS-2176
**Before**
**After**
Change for DCS-2177
**Before**
**After**
Change for DCS-2178
**Before**
**After**
Change for DCS-2179
**Before**
**After**

DCS-2176 com task list heading change

---

licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/specs/finalchecks/FinalChecksTaskListSpec.groovy
licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/specs/postDecision/CaTaskListSpec.groovy
server/routes/viewModels/taskLists/tasks/bassAddress.js
server/views/bassReferral/bassOffer.pug
server/views/bassReferral/bassWithdrawn.pug
server/views/bassReferral/includes/bassRequestActions.pug
server/views/bassReferral/includes/newBassForm.pug
server/views/bassReferral/unsuitable.pug
test/routes/bassReferral.test.js
test/routes/viewModels/taskListModelsCA.test.js
test/routes/viewModels/taskListModelsDM.test.js
test/routes/viewModels/taskLists/dmTasks.test.js

Small content changes - BASS replaced with CAS2
Change for DCS-2181
**Before**
**After**
Change for DCS-2182
**Before**
**After**
Change for DCS-2183
**Before**
**After**
Change for DCS-2184
**Before**
**After**
Change for DCS-2186
**Before**
**After**

DCS-2181 ca review task list heading content change

---

server/views/review/bassOffer.pug

Small content changes - BASS replaced with CAS2
**Before** 
**After**

DCS-2188 dm review cas2 content change

---

server/views/bassReferral/includes/bassAddressForm.pug

DCS-2190 ca licence creation cas2 content change

---

server/routes/viewModels/taskLists/tasks/bassAddress.js
server/routes/viewModels/taskLists/tasks/ro/bassArea.js
server/views/bassReferral/bassAreaCheck.pug
server/views/bassReferral/bassOffer.pug
server/views/review/includes/bassArea.pug
server/views/review/includes/bassRequest.pug
test/routes/viewModels/taskListModelsCA.test.js
test/routes/viewModels/taskListModelsDM.test.js
test/routes/viewModels/taskLists/tasks/bassAddress.test.js
test/routes/viewModels/taskLists/tasks/ro/bassArea.test.js

Additional BASS to CAS2 content changes. Further changes to follow in another ticket but trying to keep the extra changes manageable to look at. See ticket for screen shots and details: https://dsdmoj.atlassian.net/browse/DCS-2194

DCS-2194 CA Eligibility Curfew address content change

---

server/routes/viewModels/taskLists/tasks/bassAddress.js
server/routes/viewModels/taskLists/tasks/ca/curfewAddress.js
server/services/licence/licenceStatusLabels.js
server/views/bassReferral/rejected.pug
test/routes/bassReferral.test.js
test/routes/viewModels/taskLists/tasks/ca/curfewAddress.test.js
test/services/licence/licenceStatusLabels.test.js

Additional BASS to CAS2 content changes. See ticket for screen shots and details: https://dsdmoj.atlassian.net/browse/DCS-2196

DCS-2196 ca review tasklist cas2 area rejected alert content change

---

server/routes/caseList.js
server/routes/viewModels/taskLists/tasks/bassAddress.js
server/services/licence/licenceStatusLabels.js
server/views/review/bassOffer.pug
server/views/review/includes/licenceSummary.pug
server/views/taskList/tasks/informBassTask.pug
test/routes/viewModels/taskLists/tasks/bassAddress.test.js
test/services/licence/licenceStatusLabels.test.js

Content changes: updating all remaining user facing BASS references to CAS2.

DCS-2201 updating remaining bass withdrawn references

---

integration_test/routes/forms.test.ts
server/views/forms/eligible.pug
server/views/forms/includes/formsHeader.pug

All changes made using the updated Eligible form document, found [here](https://drive.google.com/drive/folders/12YXDIPyaH79PHVg0LtOmOPaxs8tlsunQ) for reference.

DCS-2208 update eligible form content

---

server/views/forms/approved.pug

now looks like this
==============

DCS-2214 change approved pdf form

---

server/services/config/formConfig.js
server/views/forms/refused.pug
test/services/formService.test.ts

DCS-2213 updated refused.pug and config

---

licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/pages/finalchecks/FinalChecksUndulyLenientSentencePage.groovy
licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/specs/finalchecks/FinalChecksSpec.groovy
licences-specs/src/test/resources/licences/decision/approved-bass.json
licences-specs/src/test/resources/licences/decision/approved.json
licences-specs/src/test/resources/licences/decision/mandatory-check-completed.json
licences-specs/src/test/resources/licences/decision/mandatory-check-required.json
licences-specs/src/test/resources/licences/decision/refused.json
licences-specs/src/test/resources/licences/finalchecks/final-checks-done.json
licences-specs/src/test/resources/licences/finalchecks/serious-offence-on-remand.json
licences-specs/src/test/resources/licences/postDecision/address-withdrawn-new.json
server/data/licenceTypes.ts
server/routes/config/finalChecks.js
server/routes/viewModels/taskLists/tasks/finalChecks.js
server/services/config/formsAndSections.js
server/services/licence/licenceStatus.ts
server/services/licence/licenceStatusTypes.ts
server/statistics/LicenceStatisticsCollector.ts
server/views/finalChecks/undulyLenientSentence.pug
server/views/review/finalChecks.pug
test/routes/finalChecks.test.js
test/routes/viewModels/taskLists/tasks/finalChecks.test.js
test/services/formValidation.test.ts
test/services/licence/licenceStatus.test.ts

Check page and warning added to CA review

DCS-2222 add unduly lenient sentence final check

---

licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/pages/finalchecks/FinalChecksSegregationPage.groovy
licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/specs/finalchecks/FinalChecksSpec.groovy
licences-specs/src/test/resources/licences/decision/approved-bass.json
licences-specs/src/test/resources/licences/decision/approved.json
licences-specs/src/test/resources/licences/decision/mandatory-check-completed.json
licences-specs/src/test/resources/licences/decision/mandatory-check-required.json
licences-specs/src/test/resources/licences/decision/refused.json
licences-specs/src/test/resources/licences/finalchecks/final-checks-done.json
licences-specs/src/test/resources/licences/finalchecks/serious-offence-on-remand.json
licences-specs/src/test/resources/licences/postDecision/address-withdrawn-new.json
server/data/licenceTypes.ts
server/routes/config/finalChecks.js
server/routes/viewModels/taskLists/tasks/finalChecks.js
server/services/config/formsAndSections.js
server/services/licence/licenceStatus.ts
server/services/licence/licenceStatusTypes.ts
server/statistics/LicenceStatisticsCollector.ts
server/views/finalChecks/segregation.pug
server/views/review/finalChecks.pug
test/routes/finalChecks.test.js
test/routes/viewModels/taskLists/tasks/finalChecks.test.js
test/services/formValidation.test.ts
test/services/licence/licenceStatus.test.ts

Check page and warning added to CA review:
DM review page also added:

DCS-2223 add segregation final check

---

server/services/config/formConfig.js
test/services/formService.test.ts

**tasks**
Change the formconfig.JS file on the unsuitableReasonlabels: for 'deportationLiable: 'you are likely to be deported' to deportationLiable: 'you are being considered for deportation',
Change the formconfig.JS file on the unsuitableReasonlabels: for recalled: 'you were recalled to prison for poor behaviour during your previous early release' to recalled: 'you were recalled to prison for poor behaviour during your previous home detention curfew release'
Change the formconfig.JS file on the unsuitableReasonlabels: for serving4YearsOrMoreOverseas: 'you are serving a sentence of 4 or more years' to serving4YearsOrMoreOverseas: 'your original sentence was of 4 or more years'

CDCS-2243- content change for Unsuitable form

---

server/app.js
server/index.js
server/routes/taskList.ts
server/services/pdfService.ts
server/services/prisonerService.js
test/routes/taskList.test.js
test/services/pdfService.test.ts
test/services/prisonerService.test.ts

Switch /images prison-api calls to use system / client token

SDIT-1309 ImageResource

---

.circleci/config.yml

Update browser tools orb

---

mock-server/routes/stubs/hdcSearchableCandidates.js
server/data/nomisClientTypes.ts
server/services/roService.ts
server/utils/functionalHelpers.ts
test/services/roService.test.ts

Reverts ministryofjustice/licences#1560

Revert "CVSL-2019 COM caselist fix"

---

mock-server/routes/stubs/hdcSearchableCandidates.js
server/data/nomisClientTypes.ts
server/services/roService.ts
server/utils/functionalHelpers.ts
test/services/roService.test.ts

Reverts ministryofjustice/licences#1561

Revert "Revert "CVSL-2019 COM caselist fix""

---

server/data/licenceClient.ts
server/routes/admin/licence.ts
server/views/admin/licences/activity.pug
server/views/admin/licences/view.pug
test/data/licenceClient.test.ts
test/routes/admin/licence.test.js

Reverts ministryofjustice/licences#1567

Revert "CVSL-1814 Fixing bugs"

---

helm_deploy/licences/values.yaml
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

The Github action looks in values.yml to find the image but this project is set up a bit weird

Fixing trivy scan

---

server/routes/viewModels/taskLists/caTasks.js
server/routes/viewModels/taskLists/tasks/createLicence.js
test/routes/taskList.test.js
test/routes/viewModels/taskListModelsCA.test.js
test/routes/viewModels/taskLists/tasks/createLicence.test.js

This PR is to customise the create licence task list based on whether the licence is to be created in CVL. 
Licence to be created in HDC
Licence to be created in CVL

CVSL-2301 hide continue button and add label text when licence is to made in CVL
