ministryofjustice/licences

kudu-deploy.sh
The bash script was failing mysteriously on azure, something to
do with not being able to move temporary files from the tarball
=> Update kudu-deploy script to fix yarn installer

server/data/nomisClientBuilder.js, server/views/tasklist/index.pug, test/data/nomisClientTest.js
Struggled for bloody ages to get nock to obey request header settings and it just doesn't work the way it's documented, so there's an ugly alternative. 
See corresponding nomis mock PR
=> Use updated releases API. Set page-count header to match offender count

server/authentication/signIn.js, server/config.js, server/data/healthcheck.js, server/data/nomisClientBuilder.js, test/data/nomisClientTest.js
Moved api url and path into one config prop to avoid having to wait for webops to update terraform to give us an extra env var
=> Fix paths for elite2 api calls

server/data/healthcheck.js, server/data/nomisClientBuilder.js
Changing node_env to test instead of prod broke login because of using a dummy gateway token in test to avoid an error if you try to sign the token when it isn't in the correct format.
As long as we have a correctly formatted token in the NOMIS_GW_TOKEN env var that error won't occur and we don't need a special case for test mode. Without that special case, the login token will be valid even in test mode.
=> Rely on a valid gateway token instead of using a dummy in test env

server/app.js, server/authentication/signIn.js, server/routes/caseList.js, server/routes/send.js, server/routes/sent.js, server/services/caseListService.js, server/views/caseList/index.pug, server/views/layout.pug, test/routes/licenceConditionsTest.js, test/routes/taskListTest.js, test/services/caseListServiceTest.js, test/supertestSetup.js
In a couple of places we were passing role to the view but it's already there.
I've changed it from `profile.roleCode` to `user.role` so in any view you can always do user.role
=> Stop passing role manually

server/routes/send.js, server/services/prisonerService.js, server/views/send/ROtoCA.pug, test/routes/sendTest.js, test/services/prisonerServiceTest.js
When looking up prison address, don't fail if the prison is not found because it might just be a missing prison record and shouldn't necessarily stop the whole thing the way it would if the prisoner wasn't found.
=> Allow for missing prison address info without failing

server/routes/config/curfew.js, server/routes/hdc.js, server/services/licenceService.js, server/utils/functionalHelpers.js, server/utils/licenceStatus.js, server/utils/routes.js, server/views/curfew/addressSafety.pug, server/views/curfew/curfewAddressReview.pug, server/views/proposedAddress/includes/addressDetail.pug, server/views/review/includes/curfewAddress.pug, server/views/taskList/curfewAddressTask.pug, test/routes/curfewTest.js, test/routes/taskListTest.js, test/services/licenceServiceTest.js, test/utils/licenceStatusTest.js, test/utils/routesTest.js
Moved the address review results into the array item.
When we know what requirements there are for an address then we could look at using one of the fields as a unique identifier rather than relying on array position.
=> moved address review items into array

server/services/caseListService.js
getLicences now returns empty array when no results
=> Remove redundant null check

server/utils/searchParser.js, server/views/review/includes/curfewHours.pug, server/views/review/includes/reportingInstructions.pug, server/views/review/includes/riskManagement.pug, server/views/search/includes/resultsTable.pug, test/utils/searchParserTest.js
Allowed commas in the search input.
Also, RO can search and find licences in all stages. If it's in the PROCESSING_RO stage, the result links to tasklist. In other stages it links to the review screen.
Had to fix some review screen views to stop them failing when a licence section is empty.
Also don't show the link when licence is UNSTARTED, because there's nothing to see and it failed out back to the caselist which was odd
=> Search fix

server/config.js
Need this as calls to get a whole prison data in live is taking more than 5 secs
=> Increase timeout for Elite2 calls

server/app.js
CSRF is used for all post requests but we don't need CSRF for our E2E test to have access to the test utils routes
=> Ensure CSRF middle does not affect test util routes

server/utils/licenceStatus.js, server/views/taskList/taskList.pug, test/routes/taskListTest.js, test/utils/licenceStatusTest.js
https://dsdmoj.atlassian.net/browse/LIC-498
In taskList, the original was
`if (addressReviewDone && !addressRejectedOrWithdrawn)` then show other tasks
where
`addressReviewDone = licenceStatus.tasks.curfewAddressReview !== 'UNSTARTED'`
The cases where the task is not UNSTARTED leaves where it is STARTED or DONE,
which includes outcomes 'withdrawn', 'rejected', 'unfinished', or 'approved'
We exclude the other tasks where 'rejected' or 'withdrawn', so that means we show the other tasks only when 'unfinished' or 'approved'.
I'm still not sure it can get the CA and be 'unfinished', but this change doesn't alter the behaviour in that case.
For the DM tasklist, we only show the other tasks when there is a suitable address, which can only be 'approved'
=> Don't show other tasks when address not approved

server/utils/licenceStatus.js, test/utils/licenceStatusTest.js
avoid error when unanswered ie 'not yes' counted as done instead of unstarted, thus breaking checks for withdrawn status
=> Consider bassRequest DONE only when specificArea is No

server/routes/send.js, server/services/notificationService.js, test/routes/sendTest.js, test/services/notificationServiceTest.js
Also clean up send route by moving to notification service.
Notifications are non-critical so if an error occurs it only needs to be logged but should not cause the handover to fail. Therefore have re-ordered code so that errors during notify will not affect send.
Also if the handover fails then notifications should not be sent, so now the order ensures that too.
=> Ensure notify errors don't interrupt sending

server/data/licenceClient.js, server/index.js, server/services/config/notificationTemplates.js, server/services/deadlineService.js, server/services/notificationService.js, server/utils/dueDates.js, test/data/licenceClientTest.js, test/services/deadlineServiceTest.js, test/services/notificationServiceTest.js, test/utils/dueDatesTest.js
Sorry there's quite a bit of code in this. Two main bits - find all the cases where the dates mean they are due or due soon or overdue. There's some working day calculations required to enable this. Then send reminder notifications for each of those cases. It will be triggered by an overnight batch job in the early hours, which I've split into a subsequent PR.
I've purposely made the sending part sequential because with similar batch jobs in the batchloader app we found that it quickly caused timeouts from the nomis API. The volumes here are hard to predict but although it's quite likely there could be enough to cause timeouts if we bombard the nomis api, there won't be so many that it would take too long for an over night batch job.
=> Services to find due/overdue cases and send notifications

server/app.js, server/data/nomisClientBuilder.js, server/routes/address.js, server/routes/approval.js, server/routes/config/approval.js, server/routes/config/eligibility.js, server/routes/config/finalChecks.js, server/routes/eligibility.js, server/routes/finalChecks.js, server/routes/routeWorkers/standard.js, server/services/config/approvalStatuses.js, server/services/nomisPushService.js, test/data/nomisClientTest.js, test/routes/approvalTest.js, test/routes/eligibilityTest.js, test/routes/finalChecksTest.js, test/routes/proposedAddressTest.js, test/routes/routeWorkers/standardTest.js, test/services/nomisPushServiceTest.js
See https://dsdmoj.atlassian.net/wiki/spaces/LIC/pages/1428783438/NOMIS+Push for details
- added nomisPushService to routes that need to push to nomis
- added refusedReason to the data pushed to nomis
- when matt first added nomis pushing he copied standard route processing into approval and finalChecks routes and added nomis push, but I've reverted it back out into standard and added the nomis push into the standard router
- added formconfig used by standard router to control when to push to nomis and which licence data fields to push to nomis
- exception is optout which is handled in a non-standard way and so is done manually in the address route
- simplified nomisPushService to do a generalized lookup of approvalStatus based on type, status, and (optional) reason
- tests
=> Send approval status and refusal reason codes to nomis

server/data/nomisClientBuilder.js, server/data/userClient.js, server/routes/admin/users.js, server/services/userAdminService.js, server/views/admin/index.pug, server/views/admin/users/incompleteList.pug, server/views/admin/users/incompleteUsersTable.pug, server/views/admin/users/list.pug, server/views/admin/users/roUserDetails.pug, server/views/admin/users/usersTable.pug, test/data/nomisClientTest.js, test/data/userClientTest.js, test/routes/userAdminTest.js, test/services/userAdminServiceTest.js, test/supertestSetup.js
Adds a service to lookup incomplete users out of the audit data so that internal admins (Jim) can onboard new users.
Lots of this is just pug view files for the admin screens. Lots of it is tests.
Only used by internal admins, not user facing.
PS finding "incomplete" users means looking in the audit for users that have been sent cases (action: SEND, transitionType:caToRo), comparing those to the staff_ids table which holds all onboarded users, and if the user is missing, take the first time they appeared in the audit. Also have to call nomis to lookup the offender nomis ID matching that case.
After that, just show the list of incomplete users in a table.
=> Required RO user management

licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/pages/decision/ApprovalRefusePage.groovy, licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/specs/decision/ApprovalSpec.groovy, server/routes/config/approval.js, server/routes/routeWorkers/standard.js, server/services/config/approvalStatuses.js, server/views/approval/includes/release.pug, server/views/approval/refuseReason.pug, test/routes/approvalTest.js, test/routes/routeWorkers/standardTest.js
On the "send for refusal" paths, we now need to capture the refusal reason.
We re-use the same form as the regular refusals.
The difference is that the reason was chosen by the CA, so we pre-select that reason when showing the form.
(The DM can override by selecting other reasons)
This is the first example of requiring validation on a form that updates a different licence section, so we also need to select the target section as the source of data for validation
Having captured the refusal reason, we can configure the push to nomis for approval status just like other routes
=> Lic 946 nomis push on dm refusals

server/data/licenceClient.js, server/routes/caseList.js, server/services/caseListService.js, server/views/caseList/ROTable.pug, test/data/licenceClientTest.js, test/services/caseListServiceTest.js
Error handling for delius id lookup
Displaying user-facing errors when there are delius ID problems (for easier troubleshooting of newly-onboarded users)
=> Allow passing more meaningful error messages in caselist lookup

server/data/nomisClientBuilder.js, server/routes/address.js, server/routes/config/eligibility.js, server/routes/eligibility.js, server/routes/routeWorkers/standard.js, server/services/nomisPushService.js, test/data/nomisClientTest.js, test/routes/approvalTest.js, test/routes/eligibilityTest.js, test/routes/finalChecksTest.js, test/routes/proposedAddressTest.js, test/routes/routeWorkers/standardTest.js, test/services/nomisPushServiceTest.js
Checks passed is also used for false, not just true
Add route config to trigger checks failed push where ever needed
Change input to objects for consistency and to avoid passing unlabelled boolean
Make username consistent with prevailing usage
=> Push checks passed on failure

server/routes/config/eligibility.js, server/routes/routeWorkers/standard.js, test/routes/routeWorkers/standardTest.js
Allow pushing "checks passed" to nomis when licence data exactly matches a specified value for passing or a specified value for failing, otherwise don't send.
=> Allow sending checks passed TRUE via standard route config

.circleci/config.yml, .ebextensions/nginx.config, .elasticbeanstalk/config.yml, bin/plant-beanstalk.js, package-lock.json, package.json
We get a 502 Gateway error in some circumstances. https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=156&modal=detail&selectedIssue=LIC-960
The nginx proxy in EB gives "upstream sent too big header while reading response header from upstream".
This may actually be a red herring and there's a different error going on behind it, but I need to try this first because nothing is wrong locally, only wrong when behind nginx in AWS. If there is another error behind, fixing this part should reveal it.
The only way to configure nginx in AWS is via .ebextensions, which requires deploying a zip. We do the same thing for the batchloader where we have to configure a bigger file upload size limit.
It means we won't be able to use the Jenkins deployment for licences and have to revert to …
=> Add nginx proxy buffer config

licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/specs/assessment/TaskListSpec.groovy, server/routes/caseList.js, server/routes/viewModels/taskLists/caTasks.js, server/routes/viewModels/taskLists/dmTasks.js, server/routes/viewModels/taskLists/roTasks.js, server/routes/viewModels/taskLists/tasks/curfewAddress.js, server/routes/viewModels/taskLists/tasks/utils/actions.js, server/utils/licenceStatus.js, server/utils/licenceStatusLabels.js, server/utils/licenceStatusTransitions.js, test/routes/viewModels/taskListModelsTest.js, test/routes/viewModels/taskLists/tasks/curfewAddressTest.js, test/utils/licenceStatusLabelsTest.js, test/utils/licenceStatusTest.js, test/utils/licenceStatusTransitionsTest.js
Unfortunately this part of the app is quite intricate. It's all about determining labels and buttons and links based on what kind of user you are and what answers have been given so far during the licence processing. Because this adds a 3rd type of address with a completely different set of rules, it gets quite detailed and affects a lot of files - caselist, tasklist, and all the computations of licence status.
=> Lic 844 part3

server/routes/viewModels/taskLists/roTasks.js, server/routes/viewModels/taskLists/tasks/curfewAddress.js, test/routes/viewModels/taskListModelsTest.js, test/routes/viewModels/taskLists/tasks/curfewAddressTest.js
Shows the curfew/approved premises address task on the RO task list post-approval when approved premises is required, hides the risk task if approved premises required
For CA, the curfew adrress task links to curfew address choice when opted out
=> Post-approval task list tweaks for approved premises

server/authentication/signInService.js, server/services/jobs/notificationJobs.js, test/authentication/signInTest.js, test/services/jobs/notificationJobsTest.js
and don't set an empty username param for anonymous creds
=> Explicit function for anonymous client creds to avoid misuse

docker-compose.yml, licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/specs/pdf/PdfSpec.groovy, licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/util/LicencesApi.groovy, server/app.js
- docker-compose.yml   add - ENABLE_TEST_UTILS=true to the environment section of the licences
- service. app.js: test that enableTestUtils === 'true'. 
- LicencesApi.create: test response status code and fail if > 299.
=> LIC-fix-docker-compose 

.circleci/config.yml, .gitignore, Dockerfile, assets/sass/forms-pdf.scss, bin/build-css, licences-specs/src/test/resources/GebConfig.groovy, package-lock.json, package.json, server/config.js, server/routes/forms.js, server/views/forms/address.pug, server/views/forms/address_checks.pug, server/views/forms/address_unsuitable.pug, server/views/forms/approved.pug, server/views/forms/curfewAddress.pug, server/views/forms/eligible.pug, server/views/forms/forms-layout.pug, server/views/forms/includes/addressEntry.pug, server/views/forms/ineligible.pug, server/views/forms/no_time.pug, server/views/forms/optout.pug, server/views/forms/postponed.pug, server/views/forms/refused.pug, server/views/forms/unsuitable.pug
Whether using PhantomJS or Puppeteer to generate PDF, you have to do some extra set-up to get the required shared libs installed for Docker environments.
While working on that and while migrating the licence PDFs it became clear that using PhantomJS is a bad idea because it is now unsupported (and doesn't handle page headers). 
Therefore have migrated the PDF generator to work with Puppeteer, which seems to be the favoured tool for this sort of thing. Most of that work is in https://www.npmjs.com/package/@ministryofjustice/express-template-to-pdf
Dockerfile now loads the shared libs that are required for Puppeteer/Chrome to work in Docker.
Changing the PDF generator engine has required some tweaks to the CSS to keep the forms looking correct.
Also factored out the common layout for the …
=> Use newer PDF lib and configure it to work in Docker

server/routes/send.js, server/utils/userProfile.js, test/routes/sendTest.js, test/utils/userProfileTest.js
Favour the 'req.user.name' field over 'req.user.username' for sendingUserName
=> LIC-1027 DM name missing off the DM notification: 

.gitignore, assets/sass/licences-pdf.scss, bin/build-css, server/config.js, server/data/healthcheck.js, server/routes/config/pdf.js, server/routes/forms.js, server/routes/pdf.js, server/routes/utils/pdfUtils.js, server/services/formService.js, server/services/pdfService.js, server/services/utils/pdfFormatter.js, server/views/licences/hdc_ap.pug, server/views/licences/includes/licenceHeader.pug, server/views/licences/includes/offender.pug, test/routes/pdfTest.js, test/services/pdfServiceTest.js
1. Create a stylesheet for licences (mostly copied from the PDF service)
1. Re-organize the PDF config for forms and licences to make it cleaner
1. Modify the PDF route to check a config list of templates to make locally, sending others to the original PDF service. Now can migrate one by one (or revert back to the original in the PDF service if there's a problem)
1. Simplify some stuff to do with Vary licences because it wasn't needed - NB corresponding PR in licences PDF to match these changes for the vary templates
1. PDF page headers and footers are made a bit differently now with the new PDF module
1. Recreate the HDC_AP licence template - this is an attempt to keep it simple and ease the migration from the old template. In future it would be possible to include the Pure Grid CSS …
=> Move HDC-AP licence out of PDF service

server/data/deliusClient.js, server/data/nomisClientBuilder.js, server/routes/forms.js, server/services/formService.js, server/views/forms/forms-layout.pug, server/views/licences/hdc_ap.pug
Experimental tweaks that may fix the problem.  The only way to test this is to deploy to the pre-prod environment because the errors do not happen in any of the earlier environments (stage, local, local docker etc).
My current theory is that the pre-prod environment has a white-list of ip address for ingress:  The licences node application uses a headless Chrome browser to render PDF documents from HTML source.  This process is managed by a node module called puppet + a thin wrapper written by Alistair.  The HTML documents have links to a CSS file and font files that are served by the node app. Before this change the HTML documents prefixed the css and font file urls with the fully qualified public domain name of the licences instance.  eg …
=> LIC-1041 PDF documents not rendering in preprod environment

.circleci/config.yml, server/views/licences/hdc_ap.pug
Also remove git tag/push commands from the Circle CI deploy_stage job because they're not really needed and need a Git deploy key that has write permissions for the licences repo.
Also remove the accept_stage job from the Circle CI workflow. This job ran some of the feature tests against the APIs in the T3/T2 environments (elite2api, auth, community proxy).  The tests were failing because the community api data isn't aligned with the tests' expectations. Hence the tests are brittle in this context - and the licences 'health' end-point serves a similar purpose.
=> Lic 1046 Regression: AP licence layout is incorrect

server/authentication/oauth.js, server/authentication/signInService.js, server/config.js, server/data/deliusClient.js
Licences staging points to T3 oauth server and T2 communities-api.
We're currently getting 401s from communities api and I think it is because of this mismatch. Communities api is unable to read the token created by T3. 
`'{"error":"invalid_token","error_description":"Cannot convert access token to JSON"}'`
This should allow us to configure delius and nomis to use different oauth servers.
Also adding more logging and fixing issue where secrets with specific characters aren't accepted
=> DCS-183 Adding the ability to override delius client id and secret

licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/specs/decision/ApprovalTaskListSpec.groovy, server/routes/viewModels/taskLists/dmTasks.js, test/routes/viewModels/taskListModelsTestDM.js
When a curfew address is rejected then show the DM the Risk Management task iff the address was rejected by this task, not the 'Proposed curfew address' task.
=> DCS-181 HDC - Risk Management Information not displaying for the Decision Maker

azure-appinsights.js
Currently all traces report the same severity.
The docs for winston app insights suggest that enabling exception capturing should lead to errors being reported at level 3.
=> Attempting to set correct error severity

server/index.js, server/services/notificationService.js, server/services/roContactDetailsService.js, test/services/notificationServiceTest.js, test/services/roContactDetailServiceTest.js
This is to start to provide a central place where we can start to using delius and probation teams service as the source of org emails.
This will initially only be a fallback for when we haven't got the RO user's details in the staff ids table.
The naming might be a bit off here - going to talk to Louise about naming around RO vs COM, but RO is currently how we describe the role across licences
=> DCS-233 Extracting out service to retrieve RO contact details

server/data/deliusClient.js, server/index.js, server/services/roContactDetailsService.js, test/data/deliusClientTest.js, test/services/roContactDetailServiceTest.js
Merely logging result for now.
Also throwing error if can't get a token using client credentials when calling delius.
This would have previously thrown an auth error which would log the user out of the app but as this is client credential this situation would only happen with a programming error (so should result in a 500 status)
=> DCS-233 Calling delius when staff doesn't exist.

licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/pages/assessment/ApprovedPremisesAddressPageBassReferral.groovy, licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/pages/assessment/BassAreaCheckPage.groovy, licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/specs/assessment/BassAreaSpec.groovy, server/app.js, server/routes/bassReferral.js, server/routes/config/bassReferral.js, server/routes/forms.js, server/routes/viewModels/taskLists/caTasks.js, server/routes/viewModels/taskLists/dmTasks.js, server/routes/viewModels/taskLists/tasks/bassAddress.js, server/routes/viewModels/taskLists/tasks/bassArea.js, server/routes/viewModels/taskLists/tasks/bassOffer.js, server/routes/viewModels/taskLists/tasks/createLicence.js, server/services/utils/formValidation.js, server/services/utils/pdfFormatter/pdfFormatter.js, server/utils/licenceStatus.js, server/utils/licenceStatusLabels.js, server/utils/licenceStatusTransitions.js, server/views/bassReferral/approvedPremisesAddress.pug, server/views/bassReferral/approvedPremisesChoice.pug, server/views/bassReferral/bassAreaCheck.pug, server/views/forms/curfewAddress.pug, server/views/review/includes/approvedPremisesAddress.pug, server/views/review/includes/licenceSummary.pug, test/routes/viewModels/taskListModelsTestCA.js, test/routes/viewModels/taskListModelsTestRO.js, test/routes/viewModels/taskLists/tasks/bassAreaTest.js, test/services/formValidationTest.js, test/utils/licenceStatusLabelsTest.js, test/utils/licenceStatusTransitionsTest.js
http://localhost:3000/hdc/bassReferral/bassAreaCheck/
http://localhost:3000/hdc/bassReferral/approvedPremisesAddress/
http://localhost:3000/hdc/bassReferral/approvedPremisesChoice/
Previously if the prisoner requested a Bass address, the RO didn't have the ability to change it. The RO can now override the Bass request to an Approved Premises (AP) address.
The option to use an AP address begins in the Bass Area Check screen where a new radio button group has been added asking if an AP is required. The two options are Yes and No.
If Yes is selected, the RO is taken to the AP address screen where he can enter the address details. If No is selected, the user is returned to the tasklist screen
Also previously, the bassAreaCheck page displayed the 'Is the area suitable for the offender to live …
=> DCS 203 BASS journey changed to accept Approved Premises Address

server/services/notifications/caAndDmNotificationSender.js, server/services/notifications/roNotificationSender.js, test/services/notifications/roNotificationSenderTest.js, types/licences.d.ts
This wasn't required and we were not awaiting it so passing promises through to code which expected non promises
=> DCS-248 Fixing bug where incorrectly using promise

server/services/roService.js, test/services/roServiceTest.js, types/licences.d.ts
Also enriching responsible officer with allocated state.
We don't need to explicitly info or handle the situation when the COM has not been assigned as the responsible officer:
* When sending a notification, the fact they've received the email will lead to the RO initiating the data fix
* When checking if a CA should process a case, the COM won't be the RO as this happens soon after sentencing.
Also allowing querying whether the officer is an unallocated user at higher levels rather than throwing away.
=> DCS-276 Ignoring when is COM is not the responsible officer.

migrations/20191206100315_alter_active_local_delivery_units.js
The migration to create the active_local_delivery_units table has a column called ldu_code.
The UNIQUE constraint was previously missed so a new migration has been created to alter the table and add the constraint to ldu_code
=> DCS-263-add UNIQUE constraint

migrations/20191213164035_create-warning-table.js, server/data/probationTeamsClient.js, server/data/warningClient.js, server/index.js, server/services/notifications/notificationService.js, server/services/roContactDetailsService.js, test/data/warningClientTest.js, test/services/notifications/notificationServiceTest.js, types/licences.d.ts
This provide a general error/warnings queue to expose to the internal team.
This ticket covers storing warnings whenever a CA attempts to assign a case to an RO who has an unlinked account.
These ROs will not be notified that a case has been assigned to them - and some manual work needs to be done to fix the record.
There are other places where we merely log errors on things which end up biting us which could be surfaced in the queue and hopefully reduce the maintenance overhead of the service.
=> DCS-262 Recording warnings when issues occur

.circleci/config.yml, docker-compose.yml, helm_deploy/licences/templates/_envs.tpl, helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, server/config.js, server/index.js, server/services/caService.js, test/services/caServiceTest.js
This is the first part of the overall DCS-264 ticket.
Have created a continueCaToRoFeatureFlag key in config.js and passed the config object to the caService as an arg in the service building process in index.js.
The unit tests have been updated to include the the key. 
If the key is set to true, the caService will return 'null'
if the key is set to false, the caService will return the error codes or messages.
=> DCS-264-feature flag created and tests updated

job/gatherActiveLdus.js, job/run.js, log.js, server/data/audit.js, server/data/deliusClient.js
In order to prevent prison staff from processing cases for probation teams which aren't currently part of HDC, We need to populate a whitelist table with active LDU (local delivery unit) codes.
This script will return the LDUs for each licence that has been processed in the app. This will be the current LDU of the officer responsible for the offender - we will then compare these results with a list of LDUs for a probation area (officers could have moved teams or reassigned) to create a master list.
This PR also fixes an issue with the logger where `setLevels` on Winston lead to incorrect severity level reporting. This seems to be an issue with overwriting some monkey patching which the app insights instrumentation applies.  
(Also reducing the amount of logging which occurs when delius …
=> DCS-267 Adding active LDU script

server/services/notifications/caAndDmNotificationSender.js, server/services/notifications/notificationService.js, server/services/notifications/roNotificationSender.js, server/services/roContactDetailsService.js, server/services/roService.js, test/services/notifications/notificationServiceTest.js, test/services/roContactDetailServiceTest.js, types/licences.d.ts
Allow sending email to clearing house, even if the responsible has an unlinked user and staff account
=> DCS-293 Send emails for unlinked users

assets/sass/application.scss, server/views/taskList/taskListTemplate.pug, server/views/taskList/tasks/eligibilityTask.pug
1. Check the error array exists before gettings it's length property
2. Added a margin to the 'Check eligibility' row. This was present before but got removed along the way. Without the margin, the Start now button touches the horizontal rule
=> DCS-264: error length and margins

migrations/20200103140313_add_probation_area_code_to_active_local_delivery_units_table.js, server/data/activeLduClient.js, server/services/caService.js, test/data/activeLduClient.test.js
Inserted a new column in active_local_delivery_units table
The new column is probation_area_code.
This is needed to link an LDU to a probation area
Updated the addLdu and isLduPresent functions in the server/data/activeLduClient.js file as the save and search they perform need to include the probation area.
=> DCS-265: new column in activeLdu table

package-lock.json, package.json, server/config.js, server/index.js, server/services/caService.js, server/services/roContactDetailsService.js, test/services/caService.test.js, test/services/roContactDetailService.test.js
Previously we wouldn't have sent emails to ROs that didn't appear in the local staff ids table.
Now if we don't find the details in the local staff_ids table we will look in delius.
This has the negative side effect, that if a CA incorrectly processes a case when an offenders RO is in an area which isn't part of digital HDC and we find their details in delius - we will end up telling them that they need to process the case, even though they will have never seen the digital HDC service.
We have a new feature which will prevent a CA from processing a case if the RO is not part of the digital HDC service, this change will prevent the delius look up if this new feature is disabled
=> DCS-302 prevent looking up contact details, if active LDU check feature is disabled

server/app.js, server/config.js
Was relying on a non-existent 'production' property to help determine whether to use ssl.
Adding the property in
=> Re-enabling SSL for postgres connections

server/routes/config/taskListErrors.js, server/services/caService.js, server/services/notifications/notificationService.js, test/routes/taskList.test.js, test/services/caService.test.js, test/services/notifications/notificationService.test.js
We want to handle not being allocated an RO and being allocated the dummy 'Unallocated RO' user the same
as in both cases we will request that the user talks to a delius user and gets them to fix the data in delius
Also adding more context to warnings when a case is handed over to an unlinked user
=> DCS-304 Merging unallocated and not present reasons for blocking case progression

server/routes/taskList.js, server/routes/viewModels/taskLists/caTasks.js, server/services/caService.js, server/views/taskList/tasks/caBlockedTask.pug, test/routes/taskList.test.js, test/services/caService.test.js, types/licences.d.ts
We've decided that we shouldn't need to worry the user if there is no COM assigned if the COM would have been in an area outside the HDC rollout
So we'll always priorities the inactive LDU message if present.
=> DCS-304 Updating with new content and only ever block CA with at most one reason

migrations/20200113100137_insert-active-ldus-for-north-east.js, types/delius.d.ts
The north east is already live with HDC and this is to ensure that we continue to allow CAs to handover cases to ROs in the north east once we enable the CA blocking feature.
Also removing unused type definition which described the return type of a now unused delius api call.
=> DCS-267 Adding migration to activate all LDUs in the north east.

server/config.js, server/data/deliusClient.js, server/index.js, server/services/notifications/notificationService.js, server/services/notifications/roNotificationHandler.js, server/services/roContactDetailsService.js, test/data/deliusClient.test.js, test/services/notifications/notificationService.test.js, test/services/notifications/roNotificationHandler.test.js, test/services/roContactDetailService.test.js, types/delius.d.ts, types/licences.d.ts
This role is added when a prison case administrator hands over a case to a responsible officer as we have identified that that delius user should have access to the licence service.
We add a delius role to the user. When that user attempts to access the service with their delius user details, nomis oauth server will map the new delius role to the standard licence responsible officer role.
The add role is an idempotent operation - so there is no problem executing it every time an RO is assigned a case.
=> DCS-295 Adding delius hdc licences role

.eslintrc.json, server/services/lduService.js, server/views/admin/locations/ldus.pug, server/views/admin/locations/probationAreas.pug, test/services/lduService.test.js
http://localhost:3000/admin/locations/probation-areas
Probation area code appended to name
http://localhost:3000/admin/locations/probation-areas/:code/local-delivery-units
Ldus filtered by code to remove any duplicates. Displayed only first description where the same ldu may have more than one description
Extra padding to bottom of save button
=> DCS-328: Ldus reorganised and  duplicates removed

server/routes/user.js, test/routes/user.test.js
RO has system credentials and so associated set of roles assigned to res.locals in auth.js.
The role switcher only sees the RO role, and no other roles which the user could change to so it disappears.
This change ensures that the roles that are considered belong to the user token rather than the system token.
The whole auth/role handling area could do with being rewritten
=> DCS-339 Fixing issue where you could not change roles if you were an RO

server/app.js, server/data/nomisClientBuilder.js, server/index.js, server/routes/admin/licence.js, server/routes/admin/licenceSearch.js, server/services/licenceSearchService.js, server/utils/licenceStatus.js, server/views/admin/index.pug, server/views/admin/licenceSearch.pug, server/views/admin/licences/search.pug, server/views/admin/licences/view.pug, test/data/nomisClient.test.js, test/routes/admin/licence.test.js, test/routes/admin/licenceSearch.test.js, test/routes/admin/userAdmin.test.js, test/services/licenceSearchService.test.js, types/licences.d.ts
We want to add the ability for admin staff to be able to view additional information about a licence.
This allows searching for a licence based on offender number or booking id and currently just shows limited info about the offender, assigned RO and some key dates. 
In future tickets we will add additional info/actions to this page, for instance, we want to expose audit history for a licence to reduce the amount of time we need to spend when investigating support requests.
=> Add admin "search for licence" page 

server/app.js, server/data/audit.js, server/routes/admin/licence.js, server/routes/admin/licenceSearch.js, server/views/admin/licences/activity.pug, server/views/admin/licences/event.pug, server/views/admin/licences/search.pug, server/views/admin/licences/view.pug, server/views/admin/locations/ldus.pug, test/data/audit.test.js, test/routes/admin/licence.test.js, test/supertestSetup.js
Adding new screen to allow admin staff to view the audit history of a licence
<kbd>
</kbd>
Clicking on timestamp also allows viewing raw audit events:
<kbd>![Screenshot 2020-01-27 at 15 13 47](https://user-images.githubusercontent.com/1517745/73186442-a23a3b80-4117-11ea-9b48-eb38bda02f01.png)
</kbd>
=> DCS-332 Adding in history view into the admin licences screen

licences-specs/src/test/resources/GebConfig.groovy, server/services/conditionsService.js, test/services/conditionsService.test.js
This bug occurs when attempting to create the Curfew Address Check Form (one of the tasks in the RO tasklist).
If, for example, a Proposed Curfew Address is rejected, then this bug occurs.
=> DCS-312 Fix issue around retrieving conditions 

server/app.js, server/index.js, server/routes/admin/licence.js, server/views/admin/licences/activity.pug, server/views/admin/licences/notify.pug, server/views/admin/licences/view.pug, test/routes/admin/licence.test.js
When a licence is with an RO, this changes adds a new button to the licence view which will allow an admin staff to send the email notification to the RO, their team and the clearing house.
This will generate a notify event in the audit log against the admin staff member who triggered the request
=> DCS-331 Adding ability for staff to trigger notifying an RO

server/app.js, server/authentication/authInit.js, server/routes/contact.js, test/routes/contact.test.js, test/supertestSetup.js
Previously the accessing user required access to the caselist associated with the booking to view the responsible RO. 
The only info we use from NOMIS in this call is to map from booking id to nomis id, no personal info.
=> DCS-351 Relax restriction on contact page,

server/config.js, server/index.js, server/services/reminderService.js, test/services/reminderService.test.js
At the moment a job runs at 1am in the morning and hammers the community-api and then doesn't actually do anything with the data for inactive notifications.
This change prevents the work being done entirely if a specific notification is disabled
=> DCS-348 Only process active reminders

server/routes/viewModels/taskLists/dmTasks.js, server/views/taskList/taskListTemplate.pug, test/routes/taskList.test.js
http://localhost:3000/hdc/taskList/1200635
DM  tasklist displayed error messages  if DM had previously refused approval of the curfew address.
These error messages are not needed because the CA has now provided a new address for DM to consider so the approval process starts afresh
=> DCS-360-DM no longer sees errors in tasklist

server/services/roService.js, test/data/nomisClient.test.js, test/services/roService.test.js
If we don't specify offender numbers when requesting sentences, elite throws a 400 bad request.
We had a guard to protect against this but it assumed that offender numbers would always be
present in delius for each prisoner and this is not always the case.
Offenders without offender numbers would be filtered out of the request but
If all prisoners did not have offender numbers then this would result in a 400
This fixes the guard to prevent this edgecase.
=> DCS-384 Fixing issue with bad request when getting sentences from elite

server/data/deliusClient.js, server/routes/user.js, test/data/deliusClient.test.js, test/routes/user.test.js
Adding filtering to probation areas to exclude inactive areas or areas which represent prisons. 
Also removing super annoying bug, which only really affect internal staff (but affects them all the time, even if they are aware of it) 
Whenever you change role you get redirected to the same screen with no visual indicator, so users just wait as they think nothings happened. 
Now redirecting the `/` as users won't want to do additional changes on the `/user` page.
=> DCS-364 Filtering out dodgy probation areas 

azure/licences_log_queries.txt, server/data/nomisClientBuilder.js, server/services/roService.js, server/utils/functionalHelpers.js, test/data/nomisClient.test.js, test/services/roService.test.js
NOMIS returns a 400 "Header too large" response when ROs are assigned a large list of offenders. This is due to coercing a large list of nomis ids into a very long query string.
ROs generally shouldn't be assigned large lists of offenders but it seems a small number of LDUs have strange ways of working and do end up in this state.
We could have potentially added a POST endpoint to handle lots of offender Nos but this seemed a bit overkill for such a small edge case.
=> DCS-385 Adding batching of requests to when retrieving large numbers of sentences

azure/licences_log_queries.txt, server/routes/viewModels/taskLists/dmTasks.js, test/routes/viewModels/taskLists/dmTasks.test.js
The Decision manager was presented the rejected list when an address is rejected and an offender goes on to have a BASS address accepted.
This is because we don't track decisions associated with an address and BASS and normal addresses are just stored as different parts of the JSON payload.
We can't prioritise decisons made associated with one type of address over the other.
This tweaks how we determine which task list to present.
This is merely the whacking one mole... we have some ideas of how to fix the root cause but this is just a sticking plaster.
=> DCS-256 Fix bug where DM incorrectly sees rejected address task list

server/views/contact/deliusRo.pug, test/routes/contact.test.js
This is to aid debug issues around roll out where we seem to have duplicate staff records.
=> DCS-395 Adding staff code to ro details

server/routes/config/authorisation.js, server/views/taskList/taskListTemplate.pug, test/routes/taskList.test.js
http://localhost:3000/hdc/taskList/{bookng id}
The Forms link was previously only displayed to CA's.
The link is also now presented to RO's beccause they need access to the forms.
=> DCS-240 - the RO tasklist page displays Forms link

licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/specs/TaskListGuardSpec.groovy, licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/specs/eligibility/EligibilityTaskListSpec.groovy, licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/specs/pdf/PdfSpec.groovy, server/authentication/signInService.js, server/routes/taskList.js, server/services/prisonerService.js, test/routes/taskList.test.js
Add a 'guard' to the taskList route handler. This checks the user's role, the case's stage and whether the offender has been released.  The outcome decides whether the user is shown the taskList, a read-only version of the task list or is redirected to the case list.
=> DCS-322 RO can modify licence when case is currently with CA

licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/specs/TaskListGuardSpec.groovy, server/routes/taskList.js
Refinement: Give RO READ_WRITE for an un-started case and READ_ONLY for a case at the ELIGIBILITY stage.
=> DCS-322 Give RO, CA, DM appropriate views on an offender's tasklist.

server/routes/pdf.js, server/services/config/pdfData.js, server/services/utils/pdfFormatter/pdfFormatter.js, server/views/licences/vary_hdc_pss.pug, test/routes/pdf.test.js, test/services/utils/pdfFormatter.test.js
Was surprisingly simple in the end.
More or less reverted a change that Yasin made a long time ago, but classified the first-night config data  in pdfData.js as `mandatoryPreRelease` and tweaked a bit of filtering in pdfFormatter.js
Using the `mandatoryPreRelease` value means that the first-night values can be excluded from the list of mandatory values for 'vary' cases (post release), which in turn means that when those values are missing they don't prevent creating a PDF licence.
Also tweaked some code in the process of trying to work out how it works.  No idea if its any easier to comprehend, but I understand it better now.
=> DCS-224 Fix first night curfew hours.

.circleci/config.yml, knexfile.js
Knex was relying on not verifying certificates, which was the default behaviour in node-pg < 8.0.0.
Now enabling verifying connection and making root cert available for this purpose
=> DCS-432 Fixing application start up issue by enabling SSL for knex migrations

log.js, package-lock.json, package.json, server/misc.js, test/misc.test.js
Application insights automatically instruments winston now, meaning we don't need additional dependency.
Also fixing issue where passing a string as a meta item broke logging
The signature of a log method (info, warn, error, etc..) is:  `(message: string, meta: any[]) => {}`
The current flatten meta doesn't cope with more than one meta item or items of types other than `object`.
If passed a string as a second arg, for instance in the case:
```
logger.warn(
`Error calling delius, path: '${path}', verb: 'GET', response: '${getIn(error, ['response', 'text'])}'`,
error.stack
)
```
Then it would map the string, e.g: `str = 'abc'`, result = `{'0': 'a', '1': 'b', '2': 'c'}`
Now if one or more strings are passed:
`logger.info('A message', 'a', 'is', 'here' )`
It will create a flattened object of: …
=> DCS-432 Remove duplicate logging and fix meta logging

server/routes/viewModels/taskLists/caTasks.js, server/routes/viewModels/taskLists/tasks/ca/informOffenderTask.js, test/routes/viewModels/taskListModelsCA.test.js
Also fixing wording - the forms are now held in the service so don't need to use nomis
=> DCS-391 Showing 'inform offender task' when made ineligible in post approval

server/views/taskList/taskListTemplate.pug, test/routes/taskList.test.js
This is temporary fix for a bug. There may be occasions when a CA only partly completes the HDC refusal task. In these cases the message will display a colon but with nothing to its right hand side. Fix implemented to remove the colon if the CA does not provide a corresponding refusal reason .
=> DCS-411: changes to HDC refusal message

server/data/deliusClient.ts, server/services/functionalMailboxService.ts, test/data/deliusClient.test.js, test/services/functionalMailboxService.test.ts
A community API request for probation teams can return one of:
- A 200 response and a JSON body containing an object having a "content" field that is an array of result objects
- A 200 response and a JSON body containing an object that does not have a "content" field
- A 404 response
Requests for LDUs return either
- A 200 response and a JSON body containing an object having a "content" field that is an array of result objects
- A 404 response
These cases need handling correctly.
=> DCS-253 Bug fix

server/routes/conditions.js, server/services/conditionsService.js, server/views/licenceConditions/standard.pug, test/routes/licenceConditions.test.js, test/services/conditionsService.test.js
http://localhost:3000/hdc/licenceConditions/standard/{bookingId}
If a user enters bespoke additional conditions but they are either unapproved or the user has not clicked Yes or No for approval, then these conditions are displayed in a new section called Unapproved bespoke conditions. 
Otherwise that section will show a message to say there are no unapproved bespoke conditions
<bkr>
</bkr>
<bkr>
</bkr>
=> DCS-553: unapproved bespoke conditions displayed

.circleci/config.yml, server/app.js, server/data/deliusClient.ts, server/data/nomisClientBuilder.ts, server/data/userClient.js, server/index.js, server/routes/admin/users.js, server/services/migrationService.ts, server/views/admin/users/migrate.pug, server/views/admin/users/usersTable.pug, test/data/deliusClient.test.js, test/data/nomisClient.test.js, test/data/userClient.test.js, test/mockClients.ts, test/mockServices.js, test/routes/admin/users.test.ts, test/services/migrationService.test.ts, types/delius.d.ts
Also exposing admin only endpoint to allow extracting info to work out what state RO users are in prod.
We're going to look to see:
* how many licence staff records we can delete straight away (if they are linked to missing or disabled auth users for instance)
* how many licence staff we can automatically migrate over
There will also be some users that will require some manual intervention to migrate over:
* Users with unlinked accounts
* Incorrect contact details
* Users that don't have delius accounts (e.g: app support)
* Vary users
* Possibly others
=> DCS-379 Initial shot at adding admin screen to aid migration 

server/app.js, server/data/audit.js, server/services/migrationService.ts, test/services/migrationService.test.ts
These load errors  happen due to duplicate records in delius non unique errors being thrown
There is most likely only one user in this state in prod which will need fixing but its preventing loading the rest of the records on their 'page'
=> DCS-379 Handling case when auth fails to load user data. 

server/views/admin/delius/managedOffenders.pug
Bug in pug 3.0.0.
Can't use a variable that starts with 'of' in an iteration expression. eg `each offender in offenders`. 
See  https://github.com/pugjs/pug/pull/3274
=> DCS-595 Admin page /admin/delius/managedOffenders is broken

migrations/20200810182127_DCS-594-delete-records-linked-to-disabled-and-missing-auth-users.js, server/data/licenceClient.ts, server/data/userClient.js, test/data/userClient.test.js
Implemented as a soft delete:
- knex migration:
- Added a new deleted column to staff_ids table.
- Created view v_staff_ids. (SELECT * FROM staff_ids where deleted is false)
- includes roll-back script to revert.
- all operations on staff_ids table changed to use v_staff_ids
Migrations tested locally using a dump of staff_ids table from preprod.
=> DCS-594 delete records linked to disabled and missing auth users from licences staff table

server/statistics/AuditStatisticsCollector.ts, server/statistics/booking.ts, server/statistics/types.ts
Account for cases sent from RO to CA with approved premises selected.
This only affects the statistics collection scripts and does not affect any production code.
=> DCS-590 Extend statistics collection - No production changes

migrations/20200818182127_add-delius-username-to-staff-id.js, server/data/licenceClient.ts, server/data/licenceClientTypes.ts, server/data/userClient.js, server/routes/admin/delius.js, server/services/caseListService.ts, server/services/roService.js, server/services/userAdminService.js, server/views/admin/users/roUserDetails.pug, test/data/licenceClient.test.ts, test/data/userClient.test.js, test/services/caseListService.test.js, test/services/licenceService.test.ts, test/services/roService.test.js, test/services/userAdminService.test.js
Currently to build up the RO caselist, we look up offender data using a staff code
1.) We initially search the local staff table for a mapping from auth user to delius staff code
2.) If that fails, we make a request to delius to find the staff code for the currently logged in user.
After the probation area split on the weekend, new staff codes will be generated so our mappings in 1.) will
become out of date. We hoped to migrate these users to use delius credentials to access these services but
unfortunately have not had time to organise comms.
To get round this, this change will store the users currently mapped delius username in the local db.
It will then use this as a fallback when 1.) and 2.) fail to allow retrieval of an appropriate staff code
which can then be used to retrieve …
=> DCS-609 Adding fallback to load RO caseload

server/app.js, server/config.js, server/data/audit.js, server/data/deliusClient.ts, server/routes/admin/manageRoles.js, server/services/migrationService.ts, server/views/admin/index.pug, server/views/admin/manageRoles/index.pug, server/views/admin/manageRoles/viewUserRoles.pug, test/data/deliusClient.test.js, test/mockClients.ts, test/routes/admin/manageRoles.test.ts, test/services/migrationService.test.ts, types/delius.d.ts
App support need to be able to manage HDC specific delius roles. 
These screens allow an admin staff to search for delius users by username and see what HDC specific roles they have.
It also allows them to add HDC roles.
Haven't mapped the readonly role as we aren't using it yet.
=> DCS-613 Adding screens to allow app support to manage users HDC specific delius roles

server/routes/viewModels/taskLists/tasks/bassAddress.js, server/services/licence/caTransitions.ts, test/routes/viewModels/taskListModelsCA.test.js, test/routes/viewModels/taskLists/tasks/bassAddress.test.js, test/services/licence/caTransitions.test.ts
:bug:
Prison submitted BASS area to RO.
RO updated to AP required and had added the AP address.
Only the original BASS area address is visible to the CA at the prison when expecting to see Approved Premises address.
:white_check_mark: 
Fixed this bug and added some tests to guard against regressions. 
All tests and integration tests pass but test coverage is poor to non-existent for BASS + Approved Premises.  
This change might have broken some other part of the application but I have tested the main flows in this area by hand and they all seem correct.
=> DCS-590 :bug: :white_check_mark:  BASS request + Approved Premises problem

package-lock.json, package.json, server/data/restClientBuilder.ts, server/disableUsers.ts, server/enableUsers.ts
Read a list of auth service usernames from stdin, one username per line.
Disable or enable the account for every username in the list, printing the resulting user state to stdout as JSON.
This script occurs twice, once as disableUsers.ts and again (via a soft link) as enableUsers.ts
The script chooses whether to enable or disable users from the value of process.argv[1]
If this script is included in a Docker image (as it will be if deployed to the cluster environments)
it can be run in one of the deployed pods, with input redirected from a local file. That is, a file
hosted on the machine where the kubectl command is run. Running the script in a pod means that the
script will see correctly configured environment variables for that namespace.
Such an invocation might look like:
```bash …
```
=> DCS-599 Script to disable / enable auth service users.

migrations/20200923124221_add-staff-identifier-to_staff_ids.js
🚧   Add staffIdentifier column to staff_ids table. Preparatory work to be deployed to prod.
=> DCS-632 Switch to using staffId based instead of staffCode based community-api endpoints

mock-server/routes/delius.js, server/data/deliusClient.ts, server/routes/admin/delius.js, server/routes/contact.js, server/services/caseListService.ts, server/services/notifications/roNotificationHandler.js, server/services/roService.ts, server/views/admin/delius/index.pug, server/views/admin/delius/responsibleOfficer.pug, server/views/contact/deliusRo.pug, test/routes/contact.test.ts, test/services/notifications/roNotificationHandler.test.ts, test/services/roService.test.ts
* Fixes mistake in handling response to community-api end-point `GET /offenders/nomsNumber/${offenderNo}/allOffenderManagers` which returns `staffId` not `staffIdentifier`
* Show staff identifier in RO details page linked from offender details section of task list
* Admin changes to allow search by staff identifier instead of staff code on Delius api page.
* Show staff identifier in messages and RO related information
=> DCS-632 Use staffIdentifier based instead of staffCode based community-api endpoints.

mock-server/routes/delius.js, server/services/config/formConfig.js, server/services/formService.js, server/views/forms/agency_notification.pug, test/services/formService.test.js
The form now displays the Actual Release Date as well as the Conditional Release Date.
As a side issue, a change was also made to mock-server/routes/delius.js as the logic to match the RO now uses the unique staffId rather than the non-unique staffCode value.
Agency notification form before changes
=============================
Agency notification form after changes
=============================
The relevant change is to the line "The following prisoner is due to be released on Home Detention Curfew on 13thSeptember 2019"
-------------------------
=> DCS-359 Agency Notification form displays Actual Release Date

package-lock.json, server/app.js, server/routes/vary.ts, server/services/licenceService.ts, server/services/utils/pdfFormatter/index.js, server/services/utils/pdfFormatter/pdfFormatter.js, test/routes/vary.test.ts, test/services/licenceService.test.ts
The updated address was not saving into the new version of the Licence when generated.
The vary address task only ever worked when a pre-existing licence object contained just a proposed address.  It failed to take account of objects where a bass address or approved premises address (for the bass or curfew address) had been specified.
=> DCS-427 HDC - Address change following Licence Variation update

server/views/admin/functionalMailboxes/lduWithTeams.pug, server/views/admin/locations/ldus.pug
Currently:
<kbd>
</kbd>
Will be:
<kbd>
</kbd>
And:
<kbd>
</kbd>
Will be:
<kbd>
</kbd>
=> DCS-964 increasing space on admin pages to support longer LDU descriptions

helm_deploy/licences/templates/_envs.tpl, knexfile.js, server/app.js, server/config.js, server/data/dataAccess/db.ts, server/data/nomisClientBuilder.ts, server/routes/user.js, test/routes/user.test.js
* Fix broken role handling in user.js. 
* Tweak Redis config so that it is possible to connect to 'dev' environment when running app locally. 
* For running locally against 'dev' this means port-forwarding RDS and Redis ports to localhost, connecting using TLS using a local CA cert while ignoring mismatching domains. 
* In production still use TLS and the cert, but enforce domain name matching.
* When running locally against docker images disable TLS.
=> DCS-772 Hide 'Exit to DPS link' from users for whom the link makes no sense: Bug fix.

server/app.js
Remove CA cert for Redis. It doesn't work in the docker image, isn't used elsewhere (for Redis TLS connections) , is tedious to investigate and fix and not needed.
For some reason the Redis connection code in app.js doesn't like the CA certificate, can't find it or something similar.  Odd, because the knex and db config appears to use the same code and works perfectly well.
This is only a problem when running the code from a Docker image in the Kubernetes cluster.  Running the same code outside the image (locally) works against a port-forwarded Redis (AWS) server with TLS enabled.  Note that when the code is run outside AWS TLS host checking must be disabled (rejectUnauthorized: false), whereas rejectUnauthorized would be (should be) true when the code is run in the Kubernetes cluster. …
=> DCS-772 Hide 'Exit to DPS link' from users for whom the link makes no sense (Non-NOMIS users).

licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/specs/common/CommonCaselistSpec.groovy, licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/util/Actions.groovy, package-lock.json, server/services/userService.js, server/views/layout.pug, test/services/userService.test.js
The location link text, which is in every page underneath the header, changes to 'Change your roles or location' user has multiple roles.
=> DCS-1180: location link text changed

helm_deploy/values-prod.yaml
prod ingress moved from blue to green.
This project hasn't used the 'generic-service' to construct values files so have updated the values-prod.yaml itself rather removing the annotations from dev and pre-prod to then apply in a values.yaml singularly.
=> DCS-1384 migrate prod to live

server/app.js
The browser instance within the gotenberg container relied on being able to access the pdf css from the running application. This was being blocked by the cross origin resource policy so the pdf was being generated without any styling
=> DCS-1239 Fixing pdf generation

helm_deploy/licences/Chart.yaml, helm_deploy/licences/values.yaml, helm_deploy/values-prod.yaml
Dev and Preprod to digital-prison-service-dev.
Prod to elp_alerts.
Latest version of generic-proetheus-alerts is 0.4.1, see https://github.com/ministryofjustice/hmpps-helm-charts/releases?page=1
=> DCS-1081 prometheus alerts for prod to elp_alerts slack channel

licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/specs/assessment/LicenceConditionsSpec.groovy, server/data/licenceTypes.ts, server/services/config/conditions/v2/conditions.ts, server/services/config/conditions/v2/validation.ts
Additional extremism licence added, appears in additional licences list and if selected also shown under licence conditions section on generated pdf:
=> DCS-1767 add new extremism additional condition

helm_deploy/licences/templates/ingress.yaml
This PR is intended to test downtime moving to the new Ingress apiVersion and nginx-ingress-controller.
It will be tested in dev and potentially pre-prod. 
If the downtime is acceptable. It will then be pushed through to production at a reasonable time.
If not, we will revert this PR and raise another in favour of the [ 0 downtime process](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/networking/Switch-ingress-to-v1-ingress-controller.html#switch-to-the-new-ingress-controller-with-zero-downtime).
=> DCS-1766: 🆙 upgrade Ingress apiVersion to networking.k8s.io/v1 and nginx-ingress-controller to v1.2 

migrations/20221130124953_add-standard-conditions-version.js, package-lock.json, server/data/licenceClient.ts, server/data/licenceClientTypes.ts, server/routes/conditions.ts, server/routes/config/licenceConditions.ts, server/routes/review.ts, server/services/conditionsService.ts, server/services/config/conditionsConfig.ts, server/services/licenceService.ts, server/services/licenceWithConditionsBuilder.ts, server/services/utils/formValidation.ts, test/data/licenceClient.test.ts, test/mockServices.ts, test/routes/licenceConditions.test.ts, test/services/conditionsService.test.ts, test/services/licenceService.test.ts
**Tasks**
**Notes**
- Most of the file changes are due to the renaming `AdditionalConditionVersion` - this has been done to clarify the difference between itself and `StandardConditionsVersion`
- This change is not user-facing; this PR only sets up the ability to retrieve and persist the `StandardConditionsVersion` - a different ticket will implement this in the user-facing journeys
=> DCS-1907: ✨ Add Standard Conditions Versioning For Licences

server/services/licence/licenceStatus.ts, test/services/licence/licenceStatus.test.ts
Fix to trigger risk section displaying as Completed in the task list when bass address is suitable and a user selects No to the mandatory address checks question. 
Previously under these circumstances the risk section appeared as incomplete in the task list:
With these changes when a user completes the risk section answering No to the mandatory checks and previously bass area suitable we now see a completed risk section in the task list:
=> DCS-1959 update licence status DONE conditional for risk

server/services/licence/bassAddressState.ts, server/services/licence/licenceStatus.ts, server/services/licence/licenceStatusTypes.ts, test/routes/viewModels/taskLists/tasks/riskManagement.test.js, test/services/licence/licenceStatus.test.ts
Changing bass property conditional to check bassRequested instead of bassAreaSuitable.
=> DCS-1962 mandatory check banner fix

licences-specs/src/test/resources/licences/assessment/done.json, licences-specs/src/test/resources/licences/assessment/risks-nonDisclosableInformation.json, licences-specs/src/test/resources/licences/assessment/risks-yes.json, licences-specs/src/test/resources/licences/decision/approved-bass.json, licences-specs/src/test/resources/licences/decision/approved-missing.json, licences-specs/src/test/resources/licences/decision/approved.json, licences-specs/src/test/resources/licences/decision/refused.json, licences-specs/src/test/resources/licences/decision/risks-rejected.json, licences-specs/src/test/resources/licences/decision/unstarted.json, licences-specs/src/test/resources/licences/finalchecks/approved-premises.json, licences-specs/src/test/resources/licences/finalchecks/final-checks-done.json, licences-specs/src/test/resources/licences/finalchecks/final-checks.json, licences-specs/src/test/resources/licences/finalchecks/postponed.json, licences-specs/src/test/resources/licences/finalchecks/serious-offence-on-remand.json, licences-specs/src/test/resources/licences/finalchecks/serious-offence.json, licences-specs/src/test/resources/licences/finalchecks/unstarted.json, licences-specs/src/test/resources/licences/postDecision/address-withdrawn-new.json, licences-specs/src/test/resources/licences/postDecision/address-withdrawn.json, licences-specs/src/test/resources/licences/review/address-rejected-electricity.json, licences-specs/src/test/resources/licences/review/address-rejected.json, licences-specs/src/test/resources/licences/review/no-conditions.json, licences-specs/src/test/resources/licences/review/normal-ems.json, licences-specs/src/test/resources/licences/review/normal.json, licences-specs/src/test/resources/licences/review/risks-nonDisclosable.json, licences-specs/src/test/resources/licences/review/risks.json, server/routes/risk.ts, server/views/forms/curfewAddress.pug, server/views/review/risk.pug
To avoid old risk section questions displaying if no risk version present have changed conditionals to check for risk version 1 which following the data migration should always be present for old or in progress licences. Now version 2 content will be displayed as default.
=> DCS-1963 make risk view default content version 2

feature.env, helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/pages/assessment/RiskManagementV3Page.groovy, licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/specs/assessment/RiskManagementV3Spec.groovy, server/config.js, server/routes/config/risk.ts, server/routes/risk.ts, server/routes/viewModels/taskLists/tasks/riskManagement.js, server/services/licence/licenceStatus.ts, server/views/forms/curfewAddress.pug, server/views/forms/includes/riskV3.pug, server/views/review/includes/licenceSummary.pug, server/views/review/includes/riskManagementV3.pug, server/views/review/risk.pug, server/views/risk/riskManagementV3.pug, test/routes/viewModels/taskLists/tasks/riskManagement.test.js, test/services/formValidation.test.ts, test/services/licence/licenceStatus.test.ts
Added managing offender safely in the community question as a new version of the risk management section of the licence:
**COM checks view page:**
**With text box if user selects No:**
**Validation message also added as shown on the review page before a COM sends a case back to the CA:**
**Review page for risk section also updated following updates made is a user selects `Change` on the COM review page:**
**Curfew address check form accessed from the COM task list updated with new question:**
**CA review page also updated with new question:**
=> DCS-2238 add risk management question for managing offender safely in community

licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/pages/assessment/RiskManagementV3Page.groovy, licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/specs/assessment/RiskManagementV3Spec.groovy, server/data/licenceTypes.ts, server/routes/config/risk.ts, server/routes/viewModels/taskLists/tasks/riskManagement.js, server/services/licence/licenceStatus.ts, server/services/licence/licenceStatusTypes.ts, server/views/forms/includes/riskV3.pug, server/views/review/includes/riskManagementV3.pug, server/views/review/risk.pug, server/views/risk/riskManagementV3.pug, test/routes/viewModels/taskLists/tasks/riskManagement.test.js, test/services/formValidation.test.ts, test/services/licence/licenceStatus.test.ts
Added question required to confirm COM has consulted POM to the new version of the risk management section of the licence:
**COM checks view page:**
**Validation message also added as shown on the review page before a COM sends a case back to the CA:**
**Review page for risk section also updated following updates made is a user selects `Change` on the COM review page:**
**Task list now includes warning if user answers `No` to POM consultation question, also will display multiple warnings if required:**
**Curfew address check form accessed from the COM task list updated with new question:**
**CA review page also updated with new question and warning:**
=> Dcs 2239 risk management add pom consultation question

docker-compose-full.yml, docker-compose.yml
The latest images that would be pulled down when doing a docker-compose pull will cause auth error when starting
the integration tests. This is because of a has been a change to the token-verification-api 
It now uses SPRING_DATA_REDIS_HOST rather than SPRING_REDIS_HOST
=> DCS-2245 update docker compose files

server/services/config/formConfig.js, test/services/formService.test.ts
The new text will show on the Not Eligible form. Note only one reason will appear at any time.
=> DCS-2242, change reason text for Not Eligible form

server/services/licence/licenceStatus.ts, test/services/licence/licenceStatus.test.ts
Small fix to make sure that prison healthcare not consulted warning only displayed when a user selects Yes that it is essential for a mental healthcare plan to be in place and selects No to consulted with prison healthcare.
=> DCS-2240 risk mental healthcare plan question fix

licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/pages/TaskListPage.groovy, licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/pages/decision/ApprovalConsiderationPage.groovy, licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/specs/decision/ApprovalConsiderationSpec.groovy, licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/specs/decision/ApprovalSpec.groovy, licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/specs/decision/ConsiderationSpec.groovy, licences-specs/src/test/groovy/uk/gov/justice/digital/hmpps/licences/specs/decision/MandatoryCheckSpec.groovy, licences-specs/src/test/resources/licences/decision/consideration.json, server/routes/approval.js, server/routes/config/approval.js, server/routes/viewModels/taskLists/tasks/dm/makeFinalDecision.js, server/services/licence/licenceStatus.ts, server/services/licence/licenceStatusLabels.js, server/services/licence/licenceStatusTypes.ts, server/views/approval/consideration.pug, server/views/approval/mandatoryCheck.pug, test/routes/approval.test.js, test/routes/viewModels/taskListModelsDM.test.js, test/services/licence/licenceStatus.test.ts, test/services/licence/licenceStatusLabels.test.js
New page for a DM 'consideration' added
DM's Final decision task button will now go to new 'consideration' page instead of the refuse/allow page.
However if in previous questions, the answer to Mandatory Address checks is no, then the task list button will lead to the Mandatory Address Check warning page first (this is as per current behaviour)
**new page**
**new label for Final decision task if user answers No**
**and in caselist**
=> DCS-2241 add new page to DM approval journey

integration_test/routes/forms.test.ts, server/services/config/formConfig.js, server/services/formService.ts, server/views/forms/postponed.pug, test/services/formService.test.ts
Added versioning to postpone PDF form to display content depending on postpone version. 
**If a licence has a postpone version of 1 the PDF content will be:**
**If a licence has a postpone version of 2 the PDF content will be:**
**By default if no version is present yet (version only persisted when postpone section is completed) the PDF content will be as version 2 but not include the postpone reason:**
**Note:** 
A migration updating all licences with a postpone section present with a postpone version of 1 is required. This is because if a postpone version of 1 doesn’t exist the service will show version 2 content in the PDF. A user can access the PDF forms prior to completing the relevant section therefore by default we want to show version 2 content and only version 1 if they have …
=> DCS-2218 versioning postpone pdf form

migrations/20230602082059_add-postpone-version-init-value.js
This will set a postpone version of '1' for all currently 'active' and 'already started but not completed' licences. Is this correct for to not add to completed licences in the case of a postpone version (checking as in the case of viewing the postponed pdf form if a postpone version of 1 doesn’t exist the service will show version 2 content in the PDF. A user can access the PDF forms prior to completing the relevant section therefore by default we want to show version 2 content and only version 1 if they have completed the postpone section prior to this versioning taking place. Therefore for completed licences version 2 of the postponed pdf will display if viewed but I think this is all good). 
Not sure if the timestamp at the start of the file has to be completely exact - hard to so …
=> DCS-2246 add migration file to add postpone version to active/started licences

server/views/finalChecks/refuse.pug
Added 2 new refusal reason check boxes:
**Before**
**After**
Have checked the code and pretty sure new codes are not needed for updating NOMIS, as all refusal reasons in this category seem to be updated in NOMIS as `LIMITS`.
=> DCS-2259 add refusal reasons

package-lock.json, package.json
PR for semver security audit fix: https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
This required a breaking change update to `nodemon`, however I think this was all good as the breaking change was dropping official support for node 8 and licences is running on node 18. 
`nodemon` release notes: https://github.com/remy/nodemon/releases
```
semver  7.0.0 - 7.5.1
Severity: moderate
semver vulnerable to Regular Expression Denial of Service - https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
fix available via `npm audit fix --force`
Will install nodemon@3.0.1, which is a breaking change
node_modules/simple-update-notifier/node_modules/semver
simple-update-notifier  1.0.7 - 1.1.0
Depends on vulnerable versions of semver
node_modules/simple-update-notifier
nodemon  2.0.19 - 2.0.22
Depends on …
```
=> CVSL-1177 semver security audit fix

server/views/proposedAddress/rejected.pug, test/routes/proposedAddress.test.js
Small fix to pull through rejection reason to `Curfew address rejected` page following previous versioning work.
=> CVSL-1210 curfew address rejection reason fix

package-lock.json, package.json
Updated [notifications-node-client](https://github.com/alphagov/notifications-node-client) dependency to fix axios vulnerability:  
GHSA-wf5p-g6vw-rhxx | notifications-node-client>axios
https://github.com/alphagov/notifications-node-client/blob/main/CHANGELOG.md
=> CVSL-1489 bumped notifications-node-client to address axios vulnerability
